local BundleRegistry = {}

-- Lua-side component references (stable component_kind strings).
local C = {
  DisplayName = "display_name",
  PlayerTag = "player_tag",
  ProceduralSprite = "procedural_sprite",
  AccountId = "account_id",
  ControlledEntityGuid = "controlled_entity_guid",
  ControlledStartTarget = "controlled_start_target",
  EntityLabels = "entity_labels",
  ActionCapabilities = "action_capabilities",
  CharacterMovementController = "character_movement_controller",
  ActionQueue = "action_queue",
  ShipTag = "ship_tag",
  FlightComputer = "flight_computer",
  FlightEnvelopeProfile = "flight_envelope_profile",
  AfterburnerState = "afterburner_state",
  FlightTuning = "flight_tuning",
  MaxVelocityMps = "max_velocity_mps",
  HealthPool = "health_pool",
  Destructible = "destructible",
  OwnerId = "owner_id",
  MassKg = "mass_kg",
  SizeM = "size_m",
  CollisionProfile = "collision_profile",
  CollisionOutlineM = "collision_outline_m",
  CollisionAabbM = "collision_aabb_m",
  ContactResolutionM = "contact_resolution_m",
  ScannerComponent = "scanner_component",
  VisibilityRangeBuffM = "visibility_range_buff_m",
  SignalSignature = "signal_signature",
  VisualAssetId = "visual_asset_id",
  SpriteShaderAssetId = "sprite_shader_asset_id",
  RuntimeRenderLayerOverride = "runtime_render_layer_override",
  MapIcon = "map_icon",
  WorldPosition = "world_position",
  WorldRotation = "world_rotation",
  BaseMassKg = "base_mass_kg",
  CargoMassKg = "cargo_mass_kg",
  ModuleMassKg = "module_mass_kg",
  TotalMassKg = "total_mass_kg",
  MassDirty = "mass_dirty",
  AvianPosition = "avian_position",
  AvianRotation = "avian_rotation",
  AvianLinearVelocity = "avian_linear_velocity",
  AvianAngularVelocity = "avian_angular_velocity",
  AvianRigidBody = "avian_rigid_body",
  AvianMass = "avian_mass",
  AvianAngularInertia = "avian_angular_inertia",
  AvianLinearDamping = "avian_linear_damping",
  AvianAngularDamping = "avian_angular_damping",
  Hardpoint = "hardpoint",
  ParentGuid = "parent_guid",
  MountedOn = "mounted_on",
  PlanetBodyShaderSettings = "planet_body_shader_settings",
  StellarLightSource = "stellar_light_source",
  StaticLandmark = "static_landmark",
  PublicVisibility = "public_visibility",
  Engine = "engine",
  EnvironmentLightingState = "environment_lighting_state",
  FuelTank = "fuel_tank",
  AfterburnerCapability = "afterburner_capability",
  ShaderParameterSet = "shader_parameter_set",
  WeaponTag = "weapon_tag",
  BallisticWeapon = "ballistic_weapon",
  AmmoCount = "ammo_count",
  ScriptState = "script_state",
  RegistrySource = "registry_source",
  AsteroidField = "asteroid_field",
  AsteroidFieldLayout = "asteroid_field_layout",
  AsteroidFieldPopulation = "asteroid_field_population",
  AsteroidFieldDamageState = "asteroid_field_damage_state",
  AsteroidFieldMember = "asteroid_field_member",
  AsteroidFractureProfile = "asteroid_fracture_profile",
  AsteroidResourceProfile = "asteroid_resource_profile",
  AsteroidFieldAmbient = "asteroid_field_ambient",
}

local SHIP_REQUIRED_COMPONENT_KINDS = {
  C.DisplayName,
  C.ShipTag,
  C.ControlledStartTarget,
  C.EntityLabels,
  C.ActionCapabilities,
  C.ActionQueue,
  C.FlightComputer,
  C.FlightEnvelopeProfile,
  C.AfterburnerState,
  C.FlightTuning,
  C.MaxVelocityMps,
  C.HealthPool,
  C.Destructible,
  C.OwnerId,
  C.MassKg,
  C.SizeM,
  C.CollisionProfile,
  C.CollisionOutlineM,
  C.CollisionAabbM,
  C.ScannerComponent,
  C.VisibilityRangeBuffM,
  C.VisualAssetId,
  C.MapIcon,
  C.BaseMassKg,
  C.CargoMassKg,
  C.ModuleMassKg,
  C.TotalMassKg,
  C.MassDirty,
  C.ScriptState,
  C.AvianPosition,
  C.AvianRotation,
  C.AvianLinearVelocity,
  C.AvianAngularVelocity,
  C.AvianRigidBody,
  C.AvianMass,
  C.AvianAngularInertia,
  C.AvianLinearDamping,
  C.AvianAngularDamping,
  C.Hardpoint,
  C.ParentGuid,
  C.MountedOn,
  C.Engine,
  C.FuelTank,
  C.AfterburnerCapability,
  C.ShaderParameterSet,
  C.WeaponTag,
  C.BallisticWeapon,
  C.AmmoCount,
  C.RegistrySource,
}

local ASTEROID_REQUIRED_COMPONENT_KINDS = {
  C.DisplayName,
  C.EntityLabels,
  C.HealthPool,
  C.Destructible,
  C.OwnerId,
  C.MassKg,
  C.SizeM,
  C.CollisionProfile,
  C.CollisionOutlineM,
  C.CollisionAabbM,
  C.VisualAssetId,
  C.ProceduralSprite,
  C.SpriteShaderAssetId,
  C.MapIcon,
  C.WorldPosition,
  C.WorldRotation,
  C.AvianPosition,
  C.AvianRotation,
  C.AvianLinearVelocity,
  C.AvianAngularVelocity,
  C.AvianRigidBody,
  C.AvianLinearDamping,
  C.AvianAngularDamping,
}

local ASTEROID_FIELD_REQUIRED_COMPONENT_KINDS = {
  C.DisplayName,
  C.EntityLabels,
  C.OwnerId,
  C.MapIcon,
  C.WorldPosition,
  C.WorldRotation,
  C.AsteroidField,
  C.AsteroidFieldLayout,
  C.AsteroidFieldPopulation,
  C.AsteroidFieldDamageState,
  C.AsteroidFractureProfile,
  C.AsteroidResourceProfile,
  C.AsteroidFieldAmbient,
  C.AsteroidFieldMember,
  C.HealthPool,
  C.Destructible,
  C.MassKg,
  C.SizeM,
  C.CollisionProfile,
  C.CollisionOutlineM,
  C.CollisionAabbM,
  C.VisualAssetId,
  C.ProceduralSprite,
  C.SpriteShaderAssetId,
  C.AvianPosition,
  C.AvianRotation,
  C.AvianLinearVelocity,
  C.AvianAngularVelocity,
  C.AvianRigidBody,
  C.AvianLinearDamping,
  C.AvianAngularDamping,
}

local PLANET_REQUIRED_COMPONENT_KINDS = {
  C.DisplayName,
  C.EntityLabels,
  C.OwnerId,
  C.SizeM,
  C.StaticLandmark,
  C.SignalSignature,
  C.MapIcon,
  C.RuntimeRenderLayerOverride,
  C.SpriteShaderAssetId,
  C.WorldPosition,
  C.WorldRotation,
  C.PlanetBodyShaderSettings,
  C.StellarLightSource,
}

local ENVIRONMENT_LIGHTING_REQUIRED_COMPONENT_KINDS = {
  C.DisplayName,
  C.EntityLabels,
  C.OwnerId,
  C.PublicVisibility,
  C.EnvironmentLightingState,
}

local PLAYER_REQUIRED_COMPONENT_KINDS = {
  C.DisplayName,
  C.PlayerTag,
  C.AccountId,
  C.ControlledEntityGuid,
  C.EntityLabels,
  C.ActionCapabilities,
  C.CharacterMovementController,
  C.ActionQueue,
  C.ContactResolutionM,
  C.OwnerId,
  C.AvianPosition,
  C.AvianRotation,
  C.AvianLinearVelocity,
  C.AvianRigidBody,
  C.AvianMass,
  C.AvianAngularInertia,
  C.AvianLinearDamping,
  C.AvianAngularDamping,
  "tactical_map_ui_settings",
}

local CONTAINER_REQUIRED_COMPONENT_KINDS = {
  C.DisplayName,
  C.EntityLabels,
  C.OwnerId,
  C.SizeM,
  C.MapIcon,
  C.WorldPosition,
  C.WorldRotation,
  C.CargoMassKg,
  "inventory",
  C.HealthPool,
  C.Destructible,
}

BundleRegistry.bundle_classes = {
  player = { "player.default" },
  controllable = { "ship.wayfarer_industrial", "ship.corvette", "ship.rocinante" },
  world = { "asteroid.field", "asteroid.field_member", "planet.body", "environment.lighting" },
  -- Lightweight runtime-spawnable content (loot/encounters) authored for the
  -- `spawn_entity` intent (WS4). Spawnability is still default-deny via the
  -- script-spawnable allowlist; bundle_class is just for grouping.
  container = { "container.goods" },
}

BundleRegistry.bundles = {
  ["player.default"] = {
    bundle_class = "player",
    graph_records_script = "bundles/starter/player.lua",
    required_component_kinds = PLAYER_REQUIRED_COMPONENT_KINDS,
  },
  ["ship.wayfarer_industrial"] = {
    bundle_class = "controllable",
    graph_records_script = "bundles/ship/assembled.lua",
    required_component_kinds = {"hull_assembly", "compound_collision", "composite_visual", "interior_visual", "ship_tag", "flight_computer", "owner_id", "total_mass_kg"},
  },
  ["ship.corvette"] = {
    bundle_class = "controllable",
    graph_records_script = "bundles/ship/body.lua",
    required_component_kinds = SHIP_REQUIRED_COMPONENT_KINDS,
  },
  ["ship.rocinante"] = {
    bundle_class = "controllable",
    graph_records_script = "bundles/ship/body.lua",
    required_component_kinds = SHIP_REQUIRED_COMPONENT_KINDS,
  },
  ["asteroid.field_member"] = {
    bundle_class = "world",
    graph_records_script = "bundles/starter/asteroid_field.lua",
    required_component_kinds = ASTEROID_REQUIRED_COMPONENT_KINDS,
  },
  ["asteroid.field"] = {
    bundle_class = "world",
    graph_records_script = "bundles/starter/asteroid_field.lua",
    required_component_kinds = ASTEROID_FIELD_REQUIRED_COMPONENT_KINDS,
  },
  ["planet.body"] = {
    bundle_class = "world",
    graph_records_script = "bundles/starter/planet_body.lua",
    required_component_kinds = PLANET_REQUIRED_COMPONENT_KINDS,
  },
  ["environment.lighting"] = {
    bundle_class = "world",
    graph_records_script = "bundles/starter/environment_lighting.lua",
    required_component_kinds = ENVIRONMENT_LIGHTING_REQUIRED_COMPONENT_KINDS,
  },
  ["container.goods"] = {
    bundle_class = "container",
    graph_records_script = "bundles/container/goods.lua",
    required_component_kinds = CONTAINER_REQUIRED_COMPONENT_KINDS,
  },
}

return BundleRegistry
