import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';import{createHash}from'node:crypto';
import{VoxelVolume,encodeVoxels,meshChunk}from'../../packages/sim/src/voxels';
import{placementError,validateAssembly,type PartCatalog,type AssemblyVoxelLibrary}from'../../packages/content/src/assembly';
const out='.runtime/art-library/hull/r006',base='.runtime/art-library/hull/r004/context',read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const catalog:PartCatalog=read(`${base}/catalog.json`),library:AssemblyVoxelLibrary=read(`${base}/catalog.voxels.json`),components=read(`${out}/components.json`),added=read(`${out}/new-placements.json`);const reports=[];
for(const c of components.filter((c:{slug:string})=>c.slug.startsWith('outer-'))){const samples=read(`${out}/${c.slug}/samples.json`),v=new VoxelVolume();for(const[x,y,z,m]of samples.cells)v.set(x,y,z,m);const chunks=[];let tris=0;for(const chunk of v.chunks.values()){chunks.push({origin:[...chunk.origin],runs:encodeVoxels(chunk.cells)});tris+=meshChunk(v,chunk).length*2;}library.volumes[c.id]={cellMeters:samples.cellMeters,layers:[{chunks}]};reports.push({slug:c.slug,cells:samples.cells.length,proxyTriangles:tris});catalog.assets.push({id:c.id,label:`Outer armor ${c.slug} / r006`,category:c.category,nodes:[],bounds:c.bounds,thumbnail:`/assets/assembly/hull-review/${c.slug}/cutout.png`,visual:{url:`/assets/assembly/hull-review/${c.slug}/clean.glb`,sha256:createHash('sha256').update(readFileSync(`${out}/${c.slug}/clean.glb`)).digest('hex'),designId:'shipyard.hull.pilot-section',revision:6,bounds:c.bounds,damagePreview:'unsupported'}});}
catalog.assets=catalog.assets.filter(a=>a.id!=='part-baa1f612a3d9727de48b');delete library.volumes['part-baa1f612a3d9727de48b'];
const doorwayAsset=catalog.assets.find(a=>a.id==='part-70c422bca2d395c35ecb');if(doorwayAsset)doorwayAsset.label='Doorway frame (future door mount)';
for(const asset of catalog.assets){const url=asset.visual?.url;if(url?.includes('/hull-review/')&&!existsSync(`${out}/${url.split('/hull-review/')[1]}`))throw new Error(`Missing eagerly loaded visual for ${asset.id}: ${url}`);}
const isolated=validateAssembly(read(`${out}/wayfarer.json`),catalog),old=read(`${base}/wayfarer-final.json`);const context=validateAssembly({...old,parts:[...old.parts.filter((p:{id:string})=>!['pilot-r004-vestibule-wall-19','pilot-r004-vestibule-wall-20','pilot-r004-airlock-frame-21'].includes(p.id)),...added]},catalog);const checks=added.map((p:any)=>({id:p.id,error:placementError(p,context,catalog,library)??null}));const allIsolated=isolated.parts.map(p=>({id:p.id,error:placementError(p,isolated,catalog,library)??null}));
mkdirSync(`${out}/context`,{recursive:true});for(const path of [out,`${out}/context`]){writeFileSync(`${path}/catalog.json`,JSON.stringify(catalog));writeFileSync(`${path}/catalog.voxels.json`,JSON.stringify(library));}writeFileSync(`${out}/context/wayfarer-final.json`,JSON.stringify(context));writeFileSync(`${out}/context/wayfarer.json`,JSON.stringify(context));writeFileSync(`${out}/placement-validation.json`,JSON.stringify({reports,checks:allIsolated,newExteriorAgainstWholeShip:checks,allIsolated,proxySeamOwnership:'Existing r004 floor/wall proxies own the quantized shared inner diagonal boundary. Only the new cheek proxy inner face is inset one 1/16m sampling cell; authored visual faces retain exact coplanar contact. No interior cells were selectively removed.',authorityChanged:false},null,2));console.log(JSON.stringify({checks,isolatedFailures:allIsolated.filter(c=>c.error)},null,2));if(checks.some((c:{error:string|null})=>c.error)||allIsolated.some(c=>c.error))process.exitCode=1;
