import json,struct,hashlib
from pathlib import Path
root=Path(__file__).resolve().parents[2];out=root/'.runtime/art-library/hull/r006';cs=json.loads((out/'components.json').read_text());geo=[]
for c in cs:
 raw=(out/c['slug']/'clean.glb').read_bytes();n=struct.unpack_from('<I',raw,12)[0];g=json.loads(raw[20:20+n]);geo.append({'slug':c['slug'],'triangles':sum(g['accessors'][q['indices']]['count']//3 for m in g['meshes'] for q in m['primitives']),'primitives':sum(len(m['primitives']) for m in g['meshes']),'sha256':hashlib.sha256(raw).hexdigest(),'bytes':len(raw)})
(out/'geometry-validation.json').write_text(json.dumps(geo,indent=2));parts=json.loads((out/'wayfarer.json').read_text())['parts'];old=json.loads((out.parent/'r004/specification.json').read_text());metadata={c['slug']:c for c in old['components']}
for c in cs:
 if c['slug'] in metadata:
  for key in ['purpose','proposed_stats','service_clearance_m']:
   if key in metadata[c['slug']]:c[key]=metadata[c['slug']][key]
 else:
  c.update(purpose='Separate modular exterior structural armor outside unchanged cabin',proposed_stats={'mass_kg':250 if c['slug']=='outer-shoulder-transition' else 350,'hp':550,'status':'Proposed only; no authority change'},service_clearance_m=.8)
 c['placed_object_ids']=[p['id'] for p in parts if p['assetId']==c['id']]
old.update(revision=6,components=cs,geometry=geo);old['new_design_count']=4;old['reused_r004_design_count']=13;old['separately_reused_approved_roof_tiles']=3;old['triangle_total_placed']=sum(next((g['triangles'] for g in geo if next(c for c in cs if c['slug']==g['slug'])['id']==p['assetId']),0) for p in parts)
old['exterior_envelope']={'seam_y_m':9,'symmetric_rear_profile':[{'z':[-.25,1],'abs_outer_x':5.75},{'z':[1,2.6875],'abs_outer_x':5.625},{'z':[2.6875,3.0625],'abs_outer_x':5.375}],'rear_profile_source':'Actual last occupied strip Y8.9375..9, not full-tile protrusion AABB','side_taper_end':{'abs_x':5,'y':11},'diagonal_cheek_outer_end':{'abs_x':2,'y':13},'front_bumper_y':[13,13.5],'lower_armor_bottom_z':-.25,'cheek_bumper_top_z':1.3125,'room_expanded':False,'layer_category':'superstructure','unchanged_room_m2':20}
old['doorway_change']='Removed both vestibule sides and rear Y7 frame; preserved single Y9 frame as future separate-door mount, with floor and roof continuous.'
old['armor_theme']='Native physical pale ribs, framed service recesses, short vent/red/nameplate variants, top and bottom plate courses, dark belt, cyan fixture boxes and amber markers repeat around the unchanged outer envelope.'
old['remaining_differences']=['Whole-ship collar continuation and both external side joints require actual Shipyard visual acceptance.','Exterior shell adds structural depth outside the unchanged compact pressure-room footprint.','Damage maps remain visual-only; no damage or pressure authority.']
(out/'specification.json').write_text(json.dumps(old,indent=2));notes={'revision':6,'iterations':[{'attempt':'attempt-01','finding':'Fender skins were buried below dark core; diagonal shared proxy boundary double-counted','fix':'Exposed skins below glazing sill; assigned shared quantized boundary cells to existing inner assembly via new proxy inner-face inset only, preserving authored visual contact'},{'attempt':'attempt-02','finding':'Outer bumper covered old hull nameplate','fix':'Carried original editable marked material onto exterior central front panel'},{'attempt':'attempt-03','finding':'Outward +Y nameplate text was mirrored','fix':'Reversed U on outward face only'}],'self_review':'Outer layer visibly surrounds the smaller unchanged inner room, reaches beneath deck and carries continuous plated skins. Collar and dark-core backing require final whole-ship check.','geometry':{'placed_hull_triangles':old['triangle_total_placed'],'new_canonical_designs':4,'reused_r004_designs':13},'scope':'Isolated review and full-context draft only; no published/runtime/authority changes.','collar_split':'Roof-on join collar is now its own roof-category reusable module with 2 mirrored instances, so it hides with legacy roof edges. Main armor geometry and interfaces unchanged.'}
(out/'iteration-notes.json').write_text(json.dumps(notes,indent=2));print('placed hull triangles',old['triangle_total_placed'])
