import{TransmissionHelper,type ITransmissionHelperHolder}from'@babylonjs/loaders/glTF/2.0/Extensions/transmissionHelper';import{referenceMaterial}from'./planet_reference_materials';
import{expect,it}from'vitest';import{NullEngine}from'@babylonjs/core/Engines/nullEngine';import{Scene}from'@babylonjs/core/scene';import{PBRMaterial}from'@babylonjs/core/Materials/PBR/pbrMaterial';import{Color3}from'@babylonjs/core/Maths/math.color';import{TransformNode}from'@babylonjs/core/Meshes/transformNode';import{Mesh}from'@babylonjs/core/Meshes/mesh';import{PBRMaterialLoadingAdapter}from'@babylonjs/loaders/glTF/2.0/pbrMaterialLoadingAdapter';import{applyReferenceTransmission,acquireReferenceTransmission}from'./planet_reference_transmission';
it('matches glTF glass transmission/volume while preserving opaque cap material',()=>{const engine=new NullEngine(),scene=new Scene(engine);try{const glass=new PBRMaterial('glass',scene),expected=new PBRMaterial('glTF',scene),cap=new PBRMaterial('snow',scene);glass.indexOfRefraction=expected.indexOfRefraction=1.31;applyReferenceTransmission(glass,{transmissionFactor:.8,thicknessFactor:.04,attenuationColor:[.7,.9,1],attenuationDistance:.5});applyReferenceTransmission(cap,{});const a=new PBRMaterialLoadingAdapter(expected);a.configureTransmission();a.transmissionWeight=.8;a.configureVolume();a.geometryThinWalled=false;a.transmissionColor=new Color3(.7,.9,1);a.transmissionDepth=.5;a.volumeThickness=.04;for(const key of ['isRefractionEnabled','refractionIntensity','volumeIndexOfRefraction','minimumThickness','maximumThickness','useThicknessAsDepth','useAlbedoToTintRefraction','tintColorAtDistance']as const)expect(glass.subSurface[key]).toEqual(expected.subSurface[key]);expect(glass.subSurface.tintColor.asArray()).toEqual(expected.subSurface.tintColor.asArray());expect(glass.alpha).toBe(1);expect(cap.subSurface.isRefractionEnabled).toBe(false);expect(cap.alpha).toBe(1);}finally{scene.dispose();engine.dispose();}});
it('NullEngine shares one target and material over retained LOD swaps and disposes only after final owner',()=>{const engine=new NullEngine(),scene=new Scene(engine);try{const glass=new PBRMaterial('glass',scene);applyReferenceTransmission(glass,{transmissionFactor:.8});const lease=acquireReferenceTransmission(scene,[glass]),otherMaterial=new PBRMaterial('other',scene);applyReferenceTransmission(otherMaterial,{transmissionFactor:.6});const second=acquireReferenceTransmission(scene,[otherMaterial]);expect(second.target).toBe(lease.target);const levels=[0,1,2].map(lod=>{const root=new TransformNode('lod',scene);root.metadata={role:'planet',lod};root.setEnabled(lod===2);const mesh=new Mesh('shard',scene);mesh.parent=root;mesh.material=glass;mesh.metadata={role:'planet',trianglePlacementRanges:[{partId:'shaft'}]};return{root,mesh};});for(const desired of [0,1,2]){for(const level of levels)level.root.setEnabled(level.root.metadata.lod===desired);expect(levels.filter(v=>v.mesh.isEnabled())).toHaveLength(1);expect(levels.every(v=>v.mesh.material===glass)).toBe(true);expect(glass.subSurface.refractionTexture).toBe(lease.target);}const helper=(scene as Scene&Partial<ITransmissionHelperHolder>)._transmissionHelper;lease.dispose();expect((scene as Scene&Partial<ITransmissionHelperHolder>)._transmissionHelper).toBe(helper);expect(otherMaterial.subSurface.refractionTexture).toBe(second.target);second.dispose();expect((scene as Scene&Partial<ITransmissionHelperHolder>)._transmissionHelper).toBeUndefined();expect(otherMaterial.subSurface.refractionTexture).toBeNull();}finally{scene.dispose();engine.dispose();}});
it('rejects invalid transmission metadata instead of silently changing authored optics',()=>{const engine=new NullEngine(),scene=new Scene(engine),m=new PBRMaterial('glass',scene);try{expect(()=>applyReferenceTransmission(m,{transmissionFactor:2})).toThrow();expect(()=>applyReferenceTransmission(m,{transmissionFactor:.8,thicknessFactor:-1})).toThrow();expect(()=>applyReferenceTransmission(m,{transmissionFactor:.8,attenuationDistance:0})).toThrow();}finally{scene.dispose();engine.dispose();}});

it('wires authored glass through the material importer and preserves another owner of the same material',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 try{
  const role={name:'selected-ice',linearColor:[.2,.6,.8],roughness:.075,ior:1.31,transmissionFactor:.82,thicknessFactor:.16,attenuationColor:[.42,.72,.96],attenuationDistance:1.8};
  const glass=referenceMaterial(scene,role),cap=referenceMaterial(scene,{name:'snow',linearColor:[1,1,1],roughness:.8});
  expect(glass.indexOfRefraction).toBe(1.31);expect(glass.subSurface.refractionIntensity).toBe(.82);expect(cap.subSurface.isRefractionEnabled).toBe(false);
  const first=acquireReferenceTransmission(scene,[glass,glass]),second=acquireReferenceTransmission(scene,[glass]);first.dispose();
  expect(glass.subSurface.refractionTexture).toBe(second.target);expect(second.target).toBeDefined();second.dispose();expect(glass.subSurface.refractionTexture).toBeNull();
 }finally{scene.dispose();engine.dispose();}
});
it('borrows the existing scene helper without disposing a loader-owned target',()=>{
 const engine=new NullEngine(),scene=new Scene(engine),existing=new TransmissionHelper({},scene);
 try{const glass=referenceMaterial(scene,{name:'ice',linearColor:[1,1,1],roughness:.1,transmissionFactor:.7});const lease=acquireReferenceTransmission(scene,[glass]);expect(lease.target).toBe(existing.getOpaqueTarget());lease.dispose();expect(existing.getOpaqueTarget()).not.toBeNull();expect((scene as Scene&Partial<ITransmissionHelperHolder>)._transmissionHelper).toBe(existing);}finally{scene.dispose();engine.dispose();}
});
