import { installCursorTheme } from "@sidereal/canvas-ui/cursors";
import "@fontsource/barlow/400.css";
import "@fontsource/barlow/500.css";
import "@fontsource/barlow/600.css";
import "@fontsource/barlow-condensed/600.css";
import { startCanvasClient } from "./canvas-entry";
document.body.style.margin = "0";
installCursorTheme();
const client = startCanvasClient(document.getElementById("root")!);
if (import.meta.hot) import.meta.hot.dispose(() => client.dispose());
