import catalog from "./crew-armor.json";
import type { EquippedCharacterComponents } from "./character-components";

/**
 * Voxel crew armour kit (armor-v1). Presentation data only: part ids, fits, colourways and role
 * presets for the rigid-skinned armour GLBs under /assets/crew/armor-v1. Ownership, equipment slots,
 * mass and delivery stay with the existing inventory definitions; nothing here grants or validates
 * equipment. Generated by scripts/art_library/crew_armor_kit.py (--content-json); do not hand-edit
 * crew-armor.json.
 */
export const CREW_ARMOR_SLOTS = [
  "chest",
  "shoulders",
  "gloves",
  "belt",
  "legs",
  "boots",
  "back",
] as const;
export type CrewArmorSlot = (typeof CREW_ARMOR_SLOTS)[number];
export const CREW_MATERIAL_SLOTS = [
  "skin",
  "hair",
  "eye",
  "suit_primary",
  "suit_secondary",
  "accent",
  "metal",
  "dark",
  "emit",
  "glass",
] as const;
export type CrewMaterialSlot = (typeof CREW_MATERIAL_SLOTS)[number];
export type CrewArmorBodyVariant = "male" | "female" | "neutral";
export type CrewBodyRegion = "base" | "suit" | "gear" | "head" | "hands" | "hair";

export interface CrewArmorPart {
  id: string;
  slot: CrewArmorSlot;
  tier: 0 | 1 | 2 | 3;
  tierName: string;
  style: string;
  name: string;
  glb: string;
  sha256: string;
  bones: string[];
  socket: string | null;
  hidesBodyRegions: CrewBodyRegion[];
  slots: CrewMaterialSlot[];
  massKg: number;
  grid: number[];
  fits: Record<string, { mesh: string; tris: number }>;
  exhaust?: {
    node: string;
    bone: string;
    restVox: number[];
    radiusM: number;
    direction: number[];
  }[];
}
export type CrewArmorColourway = Record<
  Exclude<CrewMaterialSlot, "skin" | "hair" | "eye">,
  string
> & { label: string };
export interface CrewArmorPreset {
  id: string;
  name: string;
  colourway: string;
  headPreset: string;
  undersuit?: Partial<Record<"suit_primary" | "suit_secondary", string>>;
  parts: Partial<Record<CrewArmorSlot, string>>;
}
export type CrewArmorLoadout = Partial<
  Record<CrewArmorSlot, { part: string; colourway: string }>
>;

export const CREW_ARMOR_REVISION = catalog.revision;
export const CREW_ARMOR_ASSET_BASE = catalog.assetBase;
export const CREW_ARMOR_PARTS = catalog.parts as unknown as readonly CrewArmorPart[];
export const CREW_ARMOR_COLOURWAYS = catalog.colourways as unknown as Readonly<
  Record<string, CrewArmorColourway>
>;
export const CREW_ARMOR_PRESETS =
  catalog.presets as unknown as readonly CrewArmorPreset[];
const FITS = catalog.fits as unknown as Readonly<Record<string, string[]>>;
const LEGACY = catalog.legacyVisuals as unknown as Readonly<
  Record<string, { part: string; colourway: string }>
>;

export function crewArmorPart(id: string): CrewArmorPart | undefined {
  return CREW_ARMOR_PARTS.find((p) => p.id === id);
}

export function crewArmorPreset(id: string): CrewArmorPreset | undefined {
  return CREW_ARMOR_PRESETS.find((p) => p.id === id);
}

/** Torso fit for a body variant ("all" for parts that share one fit). */
export function crewArmorFit(
  part: CrewArmorPart,
  variant: CrewArmorBodyVariant,
): string {
  if (part.fits.all) return "all";
  const fit = Object.entries(FITS).find(([, v]) => v.includes(variant))?.[0];
  return fit && part.fits[fit] ? fit : Object.keys(part.fits)[0];
}

export function crewArmorMeshName(
  part: CrewArmorPart,
  variant: CrewArmorBodyVariant,
): string {
  return part.fits[crewArmorFit(part, variant)].mesh;
}

/** Content-addressed URL: the hash invalidates browser caches when a GLB changes. */
export function crewArmorAssetUrl(part: CrewArmorPart): string {
  return `${CREW_ARMOR_ASSET_BASE}/${part.glb}?v=${part.sha256.slice(0, 12)}`;
}

/** Armour slot colours for a colourway (unknown ids fall back to the first sheet colourway). */
export function crewArmorColourway(id: string): CrewArmorColourway {
  return (
    CREW_ARMOR_COLOURWAYS[id] ??
    CREW_ARMOR_COLOURWAYS[catalog.sheetColourways[0]]
  );
}

export function crewArmorLoadoutFromPreset(presetId: string): CrewArmorLoadout {
  const preset = crewArmorPreset(presetId);
  if (!preset) return {};
  const out: CrewArmorLoadout = {};
  for (const [slot, part] of Object.entries(preset.parts))
    out[slot as CrewArmorSlot] = { part: part!, colourway: preset.colourway };
  return out;
}

/**
 * Visuals for the existing (live) r008 equipment ids. Item identities, ownership and slots are
 * unchanged; helmet/visor belong to the head kit and are not mapped here.
 */
export function crewArmorLoadoutFromEquipment(
  equipped: EquippedCharacterComponents,
): CrewArmorLoadout {
  const out: CrewArmorLoadout = {};
  for (const [slot, id] of Object.entries(equipped)) {
    const visual = id ? LEGACY[id] : undefined;
    const part = visual && crewArmorPart(visual.part);
    if (part && part.slot === slot) out[part.slot] = visual;
  }
  return out;
}

/** Body regions to hide under a loadout (e.g. gloves replace the hands). */
export function crewArmorHiddenRegions(
  loadout: CrewArmorLoadout,
): CrewBodyRegion[] {
  const regions = new Set<CrewBodyRegion>();
  for (const entry of Object.values(loadout)) {
    const part = entry && crewArmorPart(entry.part);
    for (const r of part?.hidesBodyRegions ?? []) regions.add(r);
  }
  return [...regions];
}
