/**
 * Voxel crew handheld items + FX library r001 (PRESENTATION data).
 *
 * Generated by scripts/art_library/crew_items/build.py (Blender headless) into
 * crew-items-r001.json. Proposal art: not owner-approved, not published. Nothing here grants
 * inventory, combat, healing, shield or equip rights; authority stays in reducers. Items bind to
 * the CHAR-BODY r001 socket contract (socket.hand.R: origin = grip centre, +X along the barrel,
 * +Z up) and can also drive the existing r003 equipment pose controller via toEquipmentPoseItem.
 */
import raw from "./crew-items-r001.json";
import armedRaw from "./crew-items-r001-armed.json";
import {
  EQUIPMENT_POSE_PROFILES,
  type EquipmentPoseItem,
  type EquipmentPoseType,
  type EquipmentSocket,
  type PoseVector,
  validatePoseItem,
} from "./equipment-poses";

export type Vec3 = readonly [number, number, number];
export type CrewItemCategory = "ballistic" | "energy" | "medical" | "tool" | "utility";
export type CrewItemAnimationSet = "rifle" | "pistol" | "tool" | "device" | "melee" | "throw" | "carry" | "worn";
export type CrewItemSlot =
  | "primary" | "secondary" | "accent" | "trim" | "metal" | "dark" | "grip" | "emit_a" | "emit_b" | "glass";
export type CrewItemSocketName = "grip" | "support" | "muzzle" | "emitter" | "stock" | "sight" | "eye" | "display";
export type CharacterSocketName =
  | "socket.hand.R" | "socket.hand.L" | "socket.hip.R" | "socket.hip.L" | "socket.back" | "socket.belt";
/** Character action verbs a gameplay/presentation layer can request. */
export type CrewItemAction = "idle" | "aim" | "fire" | "reload" | "use" | "equip" | "carry" | "walk" | "pickup";

export interface CrewItemSocket {
  /** Item frame metres, Blender axes (+X right, +Y forward, +Z up); grip socket is the origin. */
  position: Vec3; direction: Vec3; up: Vec3;
  /** Same socket in glTF axes (+X right, +Y up, -Z forward), as authored in the GLB. */
  gltfPosition: Vec3; gltfDirection: Vec3; gltfUp: Vec3;
}
export interface CrewItemHolster {
  preset: string; socket: CharacterSocketName;
  /** Item frame relative to the character socket frame (Blender axes), quaternion w,x,y,z. */
  rotationWXYZ: readonly [number, number, number, number];
  /** Offset from the socket origin, metres, socket-local Blender axes. */
  offset: Vec3;
}
export interface CrewItemDefinition {
  id: string; name: string; label: string; subLabel: string;
  category: CrewItemCategory; animationSet: CrewItemAnimationSet;
  /** Existing r003 aim-space / pose-controller profile, or null for melee/throw/carry/worn items. */
  poseProfile: EquipmentPoseType | null;
  twoHanded: boolean; supportMode: "foregrip" | "free" | "carry";
  holster: CrewItemHolster | null;
  /** FX ids by trigger (fire, projectile, impact, use, beam, after, idle, ...). */
  fx: Readonly<Record<string, string>>;
  references: readonly string[];
  replacesLegacyAsset: string | null;
  defaultTheme: string;
  slotOverrides: Readonly<Record<string, { color: readonly number[]; emissiveStrength?: number }>>;
  slots: readonly CrewItemSlot[];
  voxelSize: number; sizeVoxels: Vec3; boundsMin: Vec3; boundsMax: Vec3;
  sockets: Readonly<Partial<Record<CrewItemSocketName, CrewItemSocket>>>;
  parts: readonly string[];
  itemAnimations: readonly { name: string; frames: number; durationS: number }[];
  clearance: readonly { name: string; center: Vec3; half: Vec3 }[];
  files: { lod0: string; lod1: string; icon: string };
  notes: string;
}
export interface CrewItemFxKey { t: number; scale: Vec3; opacity: number; emissive: number }
export interface CrewItemFxDefinition {
  id: string; label: string; subLabel: string; category: string;
  kind: "flash" | "projectile" | "beam" | "pulse" | "shell" | "burst" | "puff" | "plume" | "column";
  anchor: "muzzle" | "emitter" | "impact" | "actor" | "ground" | "item";
  voxelSize: number; durationS: number; loop: boolean;
  /** fixed = authored colours; emit_a/emit_b = recolour from the firing item's theme slot. */
  tint: "fixed" | "emit_a" | "emit_b"; blend: "additive" | "alpha";
  keys: readonly CrewItemFxKey[];
  speedMps: number | null; lengthM: number | null;
  light: { color: Vec3; intensity: number; rangeM: number } | null;
  references: readonly string[];
  layers: readonly { name: string; color: Vec3; emissiveStrength: number; alpha: number; lit: boolean }[];
  sizeM: Vec3; file: string;
}
export interface CrewItemSlotMaterial {
  color: Vec3; roughness: number; metallic: number;
  emissive?: Vec3; emissiveStrength?: number; alpha?: number;
}
export interface CrewItemCatalog {
  schema: "sidereal.crew.items/1"; revision: string; status: string; assetBase: string;
  voxelSize: number; animationFps: number;
  bodySpec: { schema: string; revision: string };
  handSocketRotationWXYZ: readonly [number, number, number, number];
  slots: readonly CrewItemSlot[]; variants: readonly string[];
  themes: Readonly<Record<string, Readonly<Record<CrewItemSlot, CrewItemSlotMaterial>>>>;
  characterSlotLink: Readonly<Record<string, string>>;
  items: readonly CrewItemDefinition[];
  fx: readonly CrewItemFxDefinition[];
}

const SOCKET_MAP: Readonly<Partial<Record<CrewItemSocketName, readonly EquipmentSocket[]>>> = {
  muzzle: ["Aim.Muzzle"], emitter: ["Aim.Direction", "Interaction.Contact"], stock: ["Contact.Shoulder"],
  sight: ["Sight.Primary"], eye: ["Sight.EyeReference"], display: ["Display.Reference"],
};
const CATEGORIES: readonly CrewItemCategory[] = ["ballistic", "energy", "medical", "tool", "utility"];
const SETS: readonly CrewItemAnimationSet[] = ["rifle", "pistol", "tool", "device", "melee", "throw", "carry", "worn"];
const CHARACTER_SOCKETS: readonly CharacterSocketName[] = [
  "socket.hand.R", "socket.hand.L", "socket.hip.R", "socket.hip.L", "socket.back", "socket.belt",
];
const finite = (v: readonly number[], n: number) => v.length === n && v.every(Number.isFinite);

/** Throws on any inconsistency: unknown FX, missing profile sockets, bad themes, off-origin grip. */
export function validateCrewItemCatalog(catalog: CrewItemCatalog): CrewItemCatalog {
  if (catalog.schema !== "sidereal.crew.items/1") throw new Error("Unsupported crew item schema");
  if (catalog.slots.length !== 10) throw new Error("Crew items use exactly ten material slots");
  const fxIds = new Set(catalog.fx.map((f) => f.id));
  if (fxIds.size !== catalog.fx.length) throw new Error("Duplicate FX id");
  for (const [name, theme] of Object.entries(catalog.themes))
    for (const slot of catalog.slots) {
      const m = theme[slot];
      if (!m || !finite(m.color, 3) || !(m.roughness >= 0 && m.roughness <= 1)) throw new Error(`Theme ${name} slot ${slot} invalid`);
    }
  const ids = new Set<string>();
  for (const item of catalog.items) {
    if (ids.has(item.id)) throw new Error(`Duplicate item ${item.id}`);
    ids.add(item.id);
    if (!CATEGORIES.includes(item.category) || !SETS.includes(item.animationSet)) throw new Error(`${item.id}: bad category/set`);
    if (!catalog.themes[item.defaultTheme]) throw new Error(`${item.id}: unknown theme ${item.defaultTheme}`);
    const grip = item.sockets.grip;
    if (!grip || grip.position.some((v) => Math.abs(v) > 1e-9)) throw new Error(`${item.id}: grip socket must be the origin`);
    for (const [name, s] of Object.entries(item.sockets))
      if (!s || !finite(s.position, 3) || !finite(s.direction, 3) || !finite(s.gltfPosition, 3))
        throw new Error(`${item.id}: socket ${name} invalid`);
    for (const [trigger, fx] of Object.entries(item.fx))
      if (!fxIds.has(fx)) throw new Error(`${item.id}: fx ${trigger} -> unknown ${fx}`);
    if (item.holster && !CHARACTER_SOCKETS.includes(item.holster.socket)) throw new Error(`${item.id}: holster socket`);
    if (item.twoHanded && item.supportMode !== "carry" && !item.sockets.support) throw new Error(`${item.id}: two-handed without support`);
    if (item.poseProfile) validatePoseItem(toEquipmentPoseItem(item));
    if (!item.files.lod0.endsWith(".glb") || !item.files.lod1.endsWith(".lod1.glb")) throw new Error(`${item.id}: files`);
  }
  for (const fx of catalog.fx) {
    if (!fx.keys.length || fx.keys[0].t !== 0 || fx.keys[fx.keys.length - 1].t !== 1) throw new Error(`${fx.id}: keys must span 0..1`);
    if (!(fx.durationS > 0)) throw new Error(`${fx.id}: duration`);
    if (fx.kind === "projectile" && !(fx.speedMps && fx.speedMps > 0)) throw new Error(`${fx.id}: projectile speed`);
    if (fx.kind === "beam" && !(fx.lengthM && fx.lengthM > 0)) throw new Error(`${fx.id}: beam length`);
  }
  return catalog;
}

export const CREW_ITEM_CATALOG: CrewItemCatalog = validateCrewItemCatalog(raw as unknown as CrewItemCatalog);
export const CREW_ITEMS: readonly CrewItemDefinition[] = CREW_ITEM_CATALOG.items;
export const CREW_ITEM_FX: readonly CrewItemFxDefinition[] = CREW_ITEM_CATALOG.fx;

export function crewItem(id: string): CrewItemDefinition {
  const found = CREW_ITEMS.find((item) => item.id === id);
  if (!found) throw new Error(`Unknown crew item ${id}`);
  return found;
}
export function crewItemFx(id: string): CrewItemFxDefinition {
  const found = CREW_ITEM_FX.find((fx) => fx.id === id);
  if (!found) throw new Error(`Unknown crew item FX ${id}`);
  return found;
}
/** Voxel r001 replacement for a legacy equipment asset id (compact-pistol -> pistol ...). */
export function crewItemForLegacyAsset(assetId: string): CrewItemDefinition | undefined {
  return CREW_ITEMS.find((item) => item.replacesLegacyAsset === assetId);
}

/** Adapter for the existing r003 aim-space pose controller (glTF-authored frame, grip origin). */
export function toEquipmentPoseItem(item: CrewItemDefinition): EquipmentPoseItem {
  if (!item.poseProfile) throw new Error(`${item.id} has no aim profile`);
  const profile = EQUIPMENT_POSE_PROFILES[item.poseProfile];
  const sockets: Partial<Record<EquipmentSocket, PoseVector>> = { "Grip.Primary": [0, 0, 0] };
  for (const [name, targets] of Object.entries(SOCKET_MAP) as [CrewItemSocketName, readonly EquipmentSocket[]][]) {
    const s = item.sockets[name];
    if (s) for (const t of targets) sockets[t] = [...s.gltfPosition] as unknown as PoseVector;
  }
  const support = item.sockets.support?.gltfPosition;
  if (support) sockets[profile.secondaryHandMode === "primary-hand" ? "SupportHandContact" : "Grip.Secondary"] = [...support] as unknown as PoseVector;
  if (!sockets["Aim.Muzzle"] && !sockets["Aim.Direction"] && item.sockets.grip) sockets["Aim.Direction"] = [0, 0, -0.3];
  return {
    version: 1, assetId: item.id, profile: item.poseProfile, sockets,
    clearance: item.clearance.map((b) => ({ name: b.name, center: b.center, half: b.half })),
    ...(item.sockets.display ? { deviceMode: "VIEW_SCREEN_DEVICE" as const } : {}),
  };
}

/** CHARACTER_SPEC v1 clip names each animation set uses (CHAR-BODY owns the clips). */
export const ANIMATION_SET_CLIPS: Readonly<Record<CrewItemAnimationSet, Readonly<Partial<Record<CrewItemAction, string>>>>> = {
  rifle: { idle: "idle_armed", aim: "aim_rifle", fire: "shoot_rifle", reload: "reload", walk: "walk", pickup: "pick_up" },
  pistol: { idle: "idle_armed", aim: "aim_pistol", fire: "shoot_pistol", reload: "reload", walk: "walk", pickup: "pick_up" },
  tool: { idle: "idle_armed", aim: "aim_pistol", use: "repair_loop", walk: "walk", pickup: "pick_up" },
  device: { idle: "idle", aim: "aim_pistol", use: "use_interact", walk: "walk", pickup: "pick_up" },
  melee: { idle: "idle_armed", use: "melee_swing", fire: "melee_swing", walk: "walk", pickup: "pick_up" },
  throw: { idle: "idle", use: "throw", fire: "throw", walk: "walk", pickup: "pick_up" },
  carry: { idle: "carry_idle", carry: "carry_idle", walk: "carry_walk", pickup: "pick_up", use: "use_interact" },
  worn: { idle: "idle", walk: "walk", use: "use_interact" },
};
/** Item-part glTF clip that plays in sync with a character action ("fire" -> slide recoil ...). */
const ITEM_CLIP_FOR_ACTION: Readonly<Partial<Record<CrewItemAction, readonly string[]>>> = {
  fire: ["fire", "use"], reload: ["reload"], use: ["use", "fire"], equip: ["deploy"], idle: ["idle"],
};
export interface CrewItemActionPlan { characterClip: string | null; itemClip: string | null; fx: string | null }
export function crewItemActionPlan(item: CrewItemDefinition, action: CrewItemAction): CrewItemActionPlan {
  const characterClip = ANIMATION_SET_CLIPS[item.animationSet][action] ?? null;
  const clips = new Set(item.itemAnimations.map((a) => a.name));
  const itemClip = (ITEM_CLIP_FOR_ACTION[action] ?? []).find((c) => clips.has(c)) ?? null;
  const fx = action === "fire" ? item.fx.fire ?? null : action === "use" ? item.fx.use ?? null : action === "idle" ? item.fx.idle ?? null : null;
  return { characterClip, itemClip, fx };
}

/** Slot material table for an item in a theme (item slot overrides only apply on its default theme). */
export function crewItemMaterials(item: CrewItemDefinition, theme = item.defaultTheme): Readonly<Record<CrewItemSlot, CrewItemSlotMaterial>> {
  const table = CREW_ITEM_CATALOG.themes[theme];
  if (!table) throw new Error(`Unknown crew item theme ${theme}`);
  if (theme !== item.defaultTheme) return table;
  const out = { ...table } as Record<CrewItemSlot, CrewItemSlotMaterial>;
  for (const [slot, o] of Object.entries(item.slotOverrides) as [CrewItemSlot, { color: readonly number[]; emissiveStrength?: number }][]) {
    const color = [o.color[0], o.color[1], o.color[2]] as unknown as Vec3;
    out[slot] = { ...out[slot], color, ...(out[slot].emissive ? { emissive: color, emissiveStrength: o.emissiveStrength ?? out[slot].emissiveStrength } : {}) };
  }
  return out;
}

export interface CrewItemFxSample { scale: Vec3; opacity: number; emissive: number; finished: boolean }
/** Pure keyframe sampler; t in seconds since spawn. Loops wrap, one-shots clamp and report finished. */
export function sampleCrewItemFx(fx: CrewItemFxDefinition, t: number): CrewItemFxSample {
  const u = fx.loop ? ((t / fx.durationS) % 1 + 1) % 1 : Math.min(1, Math.max(0, t / fx.durationS));
  const keys = fx.keys;
  let i = 0;
  while (i < keys.length - 2 && keys[i + 1].t < u) i++;
  const a = keys[i], b = keys[Math.min(i + 1, keys.length - 1)];
  const f = b.t > a.t ? Math.min(1, Math.max(0, (u - a.t) / (b.t - a.t))) : 0;
  const lerp = (x: number, y: number) => x + (y - x) * f;
  return {
    scale: [lerp(a.scale[0], b.scale[0]), lerp(a.scale[1], b.scale[1]), lerp(a.scale[2], b.scale[2])],
    opacity: lerp(a.opacity, b.opacity), emissive: lerp(a.emissive, b.emissive),
    finished: !fx.loop && t >= fx.durationS,
  };
}

/** Weapon classes baked into assets/runtime/crew/items/r001/armed-actions.glb (glTF animation
 * names `<class>.<clip>`), on the CHAR-BODY r002 rig with the support hand solved per frame. */
export type CrewArmedClass = "pistol" | "smg" | "carbine" | "rifle" | "shotgun" | "heavy" | "beam" | "rail" | "melee" | "tool";
export type CrewArmedClip = "idle_armed" | "walk_armed" | "run_armed" | "aim" | "shoot" | "reload" | "draw" | "holster";
const ARMED_BY_ITEM: Readonly<Record<string, CrewArmedClass>> = {
  pistol: "pistol", "stun-gun": "pistol", medgun: "pistol", grapple: "pistol", smg: "smg",
  "compact-carbine": "carbine", rifle: "rifle", shotgun: "shotgun", "heavy-gun": "heavy", "mining-drill": "heavy",
  "beam-rifle": "beam", "rail-rifle": "rail", baton: "melee", "utility-cutter": "melee", wrench: "melee",
};
/** Armed class whose baked clips an item plays (null for thrown/carried/worn items). */
export function crewArmedClass(item: CrewItemDefinition): CrewArmedClass | null {
  if (ARMED_BY_ITEM[item.id]) return ARMED_BY_ITEM[item.id];
  if (item.animationSet === "tool" || item.animationSet === "device") return "tool";
  if (item.animationSet === "rifle") return "rifle";
  if (item.animationSet === "pistol") return "pistol";
  return null;
}
/** glTF animation name in armed-actions.glb; melee/tool have no reload clip. */
export function crewArmedClip(item: CrewItemDefinition, clip: CrewArmedClip): string | null {
  const cls = crewArmedClass(item);
  if (!cls || (clip === "reload" && (cls === "melee" || cls === "tool"))) return null;
  return `${cls}.${clip}`;
}

export interface CrewArmedClipInfo {
  /** glTF animation name in `${CREW_ITEM_CATALOG.assetBase}armed-actions.glb`. */
  animation: string; class: CrewArmedClass; clip: CrewArmedClip; frames: number; loop: boolean;
  /** draw/holster: frame the right hand takes or releases the item; outside it the item rides its holster. */
  grabFrame: number | null; holsterFrames: readonly number[];
  /** item part clip to play in sync (slide/pump/mag) and frames that spawn the item's fire FX. */
  itemClip: string | null; fxFrames: readonly number[];
  /** measured on the body revision below: support-hand gap (m) and item voxels inside the torso/head. */
  supportErrorMaxM: number | null; bodyPenetrationMaxVoxels: number;
}
export const CREW_ARMED_CLIPS = armedRaw as unknown as {
  schema: "sidereal.crew.armed-clips/1"; revision: string; glb: string; bodyRevision: string;
  classes: readonly { class: CrewArmedClass; item: string; family: string }[];
  clips: readonly CrewArmedClipInfo[];
};
/** Everything a runtime needs to play an armed clip for an item: animation, item sync, FX and holster frames. */
export function crewArmedClipInfo(item: CrewItemDefinition, clip: CrewArmedClip): CrewArmedClipInfo | null {
  const name = crewArmedClip(item, clip);
  return name ? CREW_ARMED_CLIPS.clips.find((c) => c.animation === name) ?? null : null;
}

