import type { FlightPhysicalDefinition } from "../../sim/src/flight-definition";
/** Explicit v1 item unit masses and liquid kg/litre definitions. Snapshot of the
 * accepted inventory definitions; future gameplay/visual edits cannot silently
 * retune installed flight mass. Roots supply quantities and actual positions. */
export const INVENTORY_PHYSICAL_DEFINITIONS: readonly FlightPhysicalDefinition[] =
  [
    {
      id: "inventory:compact-pistol",
      revision: 1,
      kind: "inventory",
      massKg: 1.1,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:heavy-handgun",
      revision: 1,
      kind: "inventory",
      massKg: 1.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:carbine",
      revision: 1,
      kind: "inventory",
      massKg: 3.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:long-rifle",
      revision: 1,
      kind: "inventory",
      massKg: 4.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:scanner",
      revision: 1,
      kind: "inventory",
      massKg: 0.5,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:plasma-cutter",
      revision: 1,
      kind: "inventory",
      massKg: 2.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:medkit",
      revision: 1,
      kind: "inventory",
      massKg: 0.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:power-cell",
      revision: 1,
      kind: "inventory",
      massKg: 0.7,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:field-pack",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:resource-canister",
      revision: 1,
      kind: "inventory",
      massKg: 0.6,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-boots",
      revision: 1,
      kind: "inventory",
      massKg: 1.04,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-chest",
      revision: 1,
      kind: "inventory",
      massKg: 2.24,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.352,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-legs",
      revision: 1,
      kind: "inventory",
      massKg: 1.36,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.48,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 1.04,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.192,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.92,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-armor-expedition-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-helmet-explorer-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-helmet-explorer-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-helmet-standard-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-visor-standard-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "liquid:fuel",
      revision: 1,
      kind: "liquid",
      massKg: 0.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "liquid:water",
      revision: 1,
      kind: "liquid",
      massKg: 1,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
  ];
