import {
  CHARACTER_COMPONENTS,
  characterComponentImageUrl,
  type EquipmentSlot,
} from "./character-components";
import {
  CREW_WARDROBE,
  CREW_WARDROBE_KITS,
  WARDROBE_DEFINITION_PREFIX,
  crewWardrobeIconUrl,
} from "./crew-wardrobe";
// The r001 handheld catalog (generated by scripts/art_library/crew_items/build.py). Only its data
// is read here, so the server module does not pull in the presentation helpers of crew-items.ts.
import handheldCatalog from "./crew-items-r001.json";
/** Handheld item families (inventory filters, detail panels, HUD). */
export type HandheldCategory = "weapon" | "medical" | "tool" | "utility";
/** Versioned laboratory item definitions. Grid dimensions are storage footprints,
 * distinct from physical mesh/collision dimensions. Every item is a stable instance. */
export interface InventoryDefinition {
  id: string;
  name: string;
  width: number;
  height: number;
  massKg: number;
  assetId: string;
  equipSlot?: EquipmentSlot;
  /** Native shared-rig component, authoritative only when an owned item is equipped. */
  characterComponentId?: string;
  /** Voxel-crew wardrobe item (crew-wardrobe.ts); visual only, like characterComponentId. */
  wardrobeId?: string;
  iconUrl?: string;
  pose?: "pistol" | "rifle";
  storage?: { width: number; height: number; maxMassKg: number };
  reservoir?: { capacityLitres: number; liquidType: string };
  /**
   * The r001 handheld (crew-items.ts) this item shows in the hand, on the holster and in the grid.
   * The ONLY legacy-to-r001 art mapping; presentation only.
   */
  crewItemId?: string;
  category?: HandheldCategory;
  /** Short role from the r001 catalogue ("Sidearm", "Close range" ...), shown beside the category. */
  role?: string;
  /** Held with both hands (support hand on the item). */
  twoHanded?: boolean;
  /** Most instances that may share one grid slot. Every item is one stable UUID instance today,
   * so nothing stacks yet (1). */
  maxStack?: number;
  /**
   * Created before r001 and owned by live players: its footprint and mass never grow (existing
   * placements and carried mass stay valid), so it may be smaller than the r001 art's footprint.
   */
  legacy?: boolean;
}

interface HandheldCatalogItem {
  id: string;
  name: string;
  subLabel: string;
  category: string;
  animationSet: string;
  twoHanded: boolean;
  grid: { width: number; height: number };
}
const HANDHELD_ITEMS = (
  handheldCatalog as unknown as { items: readonly HandheldCatalogItem[] }
).items;
const HANDHELD_ASSET_BASE = (handheldCatalog as { assetBase: string })
  .assetBase;
const HANDHELD_REVISION = (handheldCatalog as { revision: string }).revision;
/** Inventory grid icon of an r001 handheld (rendered at its footprint aspect). */
export function handheldGridIconUrl(crewItemId: string): string {
  return `${HANDHELD_ASSET_BASE}icons/grid/${crewItemId}.png?revision=${HANDHELD_REVISION}`;
}
/** "RAPID FIRE" -> "Rapid fire"; "MELEE • UTILITY" -> "Melee · utility". */
function handheldRole(item: HandheldCatalogItem): string {
  const text = item.subLabel.toLowerCase().replace(/\s*•\s*/g, " · ");
  return text.charAt(0).toUpperCase() + text.slice(1);
}
function handheldCategory(item: HandheldCatalogItem): HandheldCategory {
  if (item.category === "ballistic" || item.category === "energy")
    return "weapon";
  if (item.category === "medical" || item.category === "tool")
    return item.category;
  return "utility";
}
/** Provisional unit masses (kg) of the r001 handhelds; flight mass uses the explicit v1 snapshot in
 * inventory-physical-definitions.ts. */
export const HANDHELD_MASS_KG: Readonly<Record<string, number>> = {
  pistol: 1.1,
  smg: 2.6,
  "compact-carbine": 3.2,
  rifle: 4,
  shotgun: 3.6,
  "heavy-gun": 9.5,
  grenade: 0.4,
  "beam-rifle": 3.8,
  "rail-rifle": 5.2,
  "stun-gun": 0.9,
  baton: 0.8,
  medgun: 1.4,
  medkit: 0.8,
  "utility-cutter": 2.4,
  "repair-tool": 1.6,
  welder: 1.9,
  "multi-tool": 1.2,
  "mining-drill": 6.5,
  wrench: 1.1,
  scanner: 0.5,
  "sample-scanner": 0.7,
  "data-pad": 0.4,
  "shield-emitter": 1.8,
  flashlight: 0.3,
  grapple: 1.5,
  drone: 1.6,
  "cargo-box": 6,
  "shield-pack": 3.5,
};
/**
 * Legacy definitions -> the r001 art they show (one consistent mapping, matching what the live
 * client has drawn since the voxel crew went live; `scanner` and `medkit` share their r001 id).
 */
export const LEGACY_HANDHELD_ART: Readonly<Record<string, string>> = {
  "compact-pistol": "pistol",
  "heavy-handgun": "pistol",
  carbine: "compact-carbine",
  "long-rifle": "rifle",
  "plasma-cutter": "utility-cutter",
  scanner: "scanner",
  medkit: "medkit",
};
/** The legacy footprint, shrunk (never grown) toward the r001 art footprint in the same
 * orientation (long side on the same axis). */
export function legacyHandheldFootprint(
  old: { width: number; height: number },
  art: { width: number; height: number },
) {
  const portrait = old.height > old.width;
  const [w, h] =
    portrait === art.height > art.width || old.width === old.height
      ? [art.width, art.height]
      : [art.height, art.width];
  return { width: Math.min(old.width, w), height: Math.min(old.height, h) };
}
function handheldItem(id: string): HandheldCatalogItem {
  const item = HANDHELD_ITEMS.find((i) => i.id === id);
  if (!item) throw new Error("Unknown r001 handheld " + id);
  return item;
}
/**
 * Equip slot of an r001 handheld: the hand. The worn shield pack has none yet: the back slot is the
 * backpack slot (its storage swaps on equip), and wearing a pack beside it arrives with shields.
 */
function handheldSlot(item: HandheldCatalogItem): EquipmentSlot | undefined {
  return item.animationSet === "worn" ? undefined : "hand";
}
function handheldPose(
  item: HandheldCatalogItem,
): "pistol" | "rifle" | undefined {
  if (item.animationSet === "rifle") return "rifle";
  if (item.animationSet === "pistol") return "pistol";
  return undefined;
}
function upgradeLegacy(definition: InventoryDefinition): InventoryDefinition {
  const artId = LEGACY_HANDHELD_ART[definition.id];
  if (!artId) return definition;
  const art = handheldItem(artId);
  return {
    ...definition,
    ...legacyHandheldFootprint(definition, art.grid),
    // Medical/tool/utility items are held too (their use is batch B).
    equipSlot: definition.equipSlot ?? handheldSlot(art),
    crewItemId: art.id,
    category: handheldCategory(art),
    role: handheldRole(art),
    twoHanded: art.twoHanded,
    iconUrl: handheldGridIconUrl(art.id),
    maxStack: 1,
    legacy: true,
  };
}
export const CHARACTER_ARMOR_DEFINITIONS: readonly InventoryDefinition[] =
  CHARACTER_COMPONENTS.map((c) => ({
    id: "crew-" + c.id,
    name: c.name,
    width: c.grid[0],
    height: c.grid[1],
    massKg: c.massKg,
    assetId: "crew-" + c.id,
    equipSlot: c.slot,
    characterComponentId: c.id,
    iconUrl: characterComponentImageUrl(c.id),
    ...(c.slot === "back"
      ? { storage: { width: 8, height: 6, maxMassKg: 24 } }
      : {}),
  }));
/** Wearable r006 wardrobe items (uniforms, tier 1-2 armour). Stable ids: `wardrobe-<id>`. */
export const CREW_WARDROBE_DEFINITIONS: readonly InventoryDefinition[] =
  CREW_WARDROBE.map((w) => ({
    id: WARDROBE_DEFINITION_PREFIX + w.id,
    name: w.name,
    width: w.grid[0],
    height: w.grid[1],
    massKg: w.massKg,
    assetId: WARDROBE_DEFINITION_PREFIX + w.id,
    equipSlot: w.slot,
    wardrobeId: w.id,
    iconUrl: crewWardrobeIconUrl(w.id),
    ...(w.slot === "back"
      ? { storage: { width: 8, height: 6, maxMassKg: 24 } }
      : {}),
  }));
/** The 2026-09-08 laboratory items (live instances exist; ids and footprints stay valid). */
const LAB_BASE_DEFINITIONS: readonly InventoryDefinition[] = [
  {
    id: "compact-pistol",
    name: "Compact pistol",
    width: 2,
    height: 2,
    massKg: 1.1,
    assetId: "compact-pistol",
    equipSlot: "hand",
    pose: "pistol",
  },
  {
    id: "heavy-handgun",
    name: "Heavy handgun",
    width: 2,
    height: 2,
    massKg: 1.8,
    assetId: "heavy-handgun",
    equipSlot: "hand",
    pose: "pistol",
  },
  {
    id: "carbine",
    name: "Frontier carbine",
    width: 2,
    height: 4,
    massKg: 3.2,
    assetId: "carbine",
    equipSlot: "hand",
    pose: "rifle",
  },
  {
    id: "long-rifle",
    name: "Survey rifle",
    width: 2,
    height: 5,
    massKg: 4.4,
    assetId: "long-rifle",
    equipSlot: "hand",
    pose: "rifle",
  },
  {
    id: "scanner",
    name: "Survey scanner",
    width: 1,
    height: 2,
    massKg: 0.5,
    assetId: "sample-scanner",
    equipSlot: "hand",
    pose: "pistol",
  },
  {
    id: "plasma-cutter",
    name: "Plasma cutter",
    width: 2,
    height: 3,
    massKg: 2.4,
    assetId: "plasma-cutter",
    equipSlot: "hand",
    pose: "pistol",
  },
  {
    id: "medkit",
    name: "Field medkit",
    width: 2,
    height: 2,
    massKg: 0.8,
    assetId: "medkit",
  },
  {
    id: "power-cell",
    name: "Power cell",
    width: 1,
    height: 2,
    massKg: 0.7,
    assetId: "power-cell",
  },
  {
    id: "field-pack",
    name: "Field backpack",
    width: 3,
    height: 4,
    massKg: 1.2,
    assetId: "utility-backpack",
    equipSlot: "back",
    storage: { width: 8, height: 6, maxMassKg: 24 },
  },
  {
    id: "resource-canister",
    name: "Fuel canister",
    width: 1,
    height: 2,
    massKg: 0.6,
    assetId: "resource-canister",
    reservoir: { capacityLitres: 5, liquidType: "fuel" },
  },
];
const LAB_DEFINITIONS = LAB_BASE_DEFINITIONS.map(upgradeLegacy);
/**
 * Every r001 handheld is a real item (batch A, 2026-09-29): stable id = the r001 id, footprint from
 * the art (catalog `grid`), grid icon, category, hand/back slot, provisional mass, no stacking. The
 * two r001 ids that already name a lab item (`scanner`, `medkit`) keep that legacy definition.
 */
export const HANDHELD_DEFINITIONS: readonly InventoryDefinition[] =
  HANDHELD_ITEMS.map(
    (item) =>
      LAB_DEFINITIONS.find((d) => d.id === item.id) ?? {
        id: item.id,
        name: item.name,
        width: item.grid.width,
        height: item.grid.height,
        massKg: HANDHELD_MASS_KG[item.id] ?? 1,
        assetId: item.id,
        ...(handheldSlot(item) ? { equipSlot: handheldSlot(item) } : {}),
        iconUrl: handheldGridIconUrl(item.id),
        crewItemId: item.id,
        category: handheldCategory(item),
        role: handheldRole(item),
        twoHanded: item.twoHanded,
        maxStack: 1,
        ...(handheldPose(item) ? { pose: handheldPose(item) } : {}),
      },
  );
export const INVENTORY_DEFINITIONS: readonly InventoryDefinition[] = [
  ...LAB_DEFINITIONS,
  ...HANDHELD_DEFINITIONS.filter(
    (d) => !LAB_DEFINITIONS.some((lab) => lab.id === d.id),
  ),
  ...CHARACTER_ARMOR_DEFINITIONS,
  ...CREW_WARDROBE_DEFINITIONS,
];

/**
 * Operator stocking kits for `scripts/ship_cargo.py --kit` (operator_stock_ship_cargo). The
 * handheld kits hold one of every r001 item (new instances; nothing existing is touched).
 */
export const OPERATOR_ITEM_KITS: Readonly<Record<string, readonly string[]>> = {
  ...CREW_WARDROBE_KITS,
  "weapons-and-tools": HANDHELD_DEFINITIONS.map((d) => d.id),
  weapons: HANDHELD_DEFINITIONS.filter((d) => d.category === "weapon").map(
    (d) => d.id,
  ),
  "tools-and-utility": HANDHELD_DEFINITIONS.filter(
    (d) => d.category !== "weapon",
  ).map((d) => d.id),
};
export function inventoryDefinition(id: string): InventoryDefinition {
  const found = INVENTORY_DEFINITIONS.find(
    (definition) => definition.id === id,
  );
  if (!found) throw new Error("Unknown item definition");
  return found;
}
export const CHARACTER_CARRY_LIMIT_KG = 32;
export const LIQUID_DENSITY_KG_PER_LITRE: Readonly<Record<string, number>> = {
  fuel: 0.8,
  water: 1,
};
/** Equipment visuals are derived only from the filtered inventory projection. */
export function characterEquipmentFromInventory(
  items: readonly { definitionId: string; equipmentSlot: string }[],
) {
  const result: import("./character-components").EquippedCharacterComponents =
    {};
  for (const item of items) {
    const definition = INVENTORY_DEFINITIONS.find(
      (d) => d.id === item.definitionId,
    );
    if (definition?.equipSlot !== item.equipmentSlot || !item.equipmentSlot)
      continue;
    const id =
      definition.characterComponentId ??
      (definition.wardrobeId
        ? WARDROBE_DEFINITION_PREFIX + definition.wardrobeId
        : undefined) ??
      (definition.id === "field-pack" ? "engineer-back" : undefined);
    if (id && item.equipmentSlot !== "hand")
      result[
        item.equipmentSlot as import("./character-components").CharacterEquipmentSlot
      ] = id;
  }
  return result;
}
