import type { FlightPhysicalDefinition } from "@sidereal/sim/flight-definition";
/** Explicit v1 item unit masses and liquid kg/litre definitions. Snapshot of the
 * accepted inventory definitions; future gameplay/visual edits cannot silently
 * retune installed flight mass. Roots supply quantities and actual positions. */
export const INVENTORY_PHYSICAL_DEFINITIONS: readonly FlightPhysicalDefinition[] =
  [
    {
      id: "inventory:compact-pistol",
      revision: 1,
      kind: "inventory",
      massKg: 1.1,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:heavy-handgun",
      revision: 1,
      kind: "inventory",
      massKg: 1.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:carbine",
      revision: 1,
      kind: "inventory",
      massKg: 3.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:long-rifle",
      revision: 1,
      kind: "inventory",
      massKg: 4.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:scanner",
      revision: 1,
      kind: "inventory",
      massKg: 0.5,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:plasma-cutter",
      revision: 1,
      kind: "inventory",
      massKg: 2.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:medkit",
      revision: 1,
      kind: "inventory",
      massKg: 0.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:power-cell",
      revision: 1,
      kind: "inventory",
      massKg: 0.7,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:field-pack",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:resource-canister",
      revision: 1,
      kind: "inventory",
      massKg: 0.6,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-captain-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-engineer-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-medic-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-pilot-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-security-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-boots",
      revision: 1,
      kind: "inventory",
      massKg: 1.04,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-chest",
      revision: 1,
      kind: "inventory",
      massKg: 2.24,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.352,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-legs",
      revision: 1,
      kind: "inventory",
      massKg: 1.36,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.48,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 1.04,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.192,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-marine-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.92,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-salvage-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-recon-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-scientist-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.25,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-mechanic-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-armor-expedition-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-helmet-explorer-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-helmet-explorer-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-helmet-standard-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:crew-legacy-visor-standard-visor",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    // r006 voxel-crew wardrobe (crew-wardrobe.ts), v1 unit masses.
    {
      id: "inventory:wardrobe-uniform-command",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-uniform-medical",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-uniform-engineering",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-uniform-security",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t1-chest",
      revision: 1,
      kind: "inventory",
      massKg: 3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t1-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 1,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t1-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t1-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.5,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t1-legs",
      revision: 1,
      kind: "inventory",
      massKg: 1,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t1-boots",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t1-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t2-chest",
      revision: 1,
      kind: "inventory",
      massKg: 6.5,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t2-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 2.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t2-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t2-belt",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t2-legs",
      revision: 1,
      kind: "inventory",
      massKg: 3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t2-boots",
      revision: 1,
      kind: "inventory",
      massKg: 2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-t2-back",
      revision: 1,
      kind: "inventory",
      massKg: 2.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    // EVA space suit (EVA milestone 2, 2026-09-29): wardrobe `suit-*` (suit, helmet, jetpack, mag boots).
    {
      id: "inventory:wardrobe-suit-body",
      revision: 1,
      kind: "inventory",
      massKg: 4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-suit-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 1.5,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-suit-pack",
      revision: 1,
      kind: "inventory",
      massKg: 4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-suit-boots",
      revision: 1,
      kind: "inventory",
      massKg: 3.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    // r001 handhelds (batch A, 2026-09-29), v1 unit masses (inventory.ts HANDHELD_MASS_KG).
    {
      id: "inventory:pistol",
      revision: 1,
      kind: "inventory",
      massKg: 1.1,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:smg",
      revision: 1,
      kind: "inventory",
      massKg: 2.6,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:compact-carbine",
      revision: 1,
      kind: "inventory",
      massKg: 3.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:rifle",
      revision: 1,
      kind: "inventory",
      massKg: 4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:shotgun",
      revision: 1,
      kind: "inventory",
      massKg: 3.6,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:heavy-gun",
      revision: 1,
      kind: "inventory",
      massKg: 9.5,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:grenade",
      revision: 1,
      kind: "inventory",
      massKg: 0.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:beam-rifle",
      revision: 1,
      kind: "inventory",
      massKg: 3.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:rail-rifle",
      revision: 1,
      kind: "inventory",
      massKg: 5.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:stun-gun",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:baton",
      revision: 1,
      kind: "inventory",
      massKg: 0.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:medgun",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:utility-cutter",
      revision: 1,
      kind: "inventory",
      massKg: 2.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:repair-tool",
      revision: 1,
      kind: "inventory",
      massKg: 1.6,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:welder",
      revision: 1,
      kind: "inventory",
      massKg: 1.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:multi-tool",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:mining-drill",
      revision: 1,
      kind: "inventory",
      massKg: 6.5,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wrench",
      revision: 1,
      kind: "inventory",
      massKg: 1.1,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:sample-scanner",
      revision: 1,
      kind: "inventory",
      massKg: 0.7,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:data-pad",
      revision: 1,
      kind: "inventory",
      massKg: 0.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:shield-emitter",
      revision: 1,
      kind: "inventory",
      massKg: 1.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:flashlight",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:grapple",
      revision: 1,
      kind: "inventory",
      massKg: 1.5,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:drone",
      revision: 1,
      kind: "inventory",
      massKg: 1.6,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:cargo-box",
      revision: 1,
      kind: "inventory",
      massKg: 6,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:shield-pack",
      revision: 1,
      kind: "inventory",
      massKg: 3.5,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "liquid:fuel",
      revision: 1,
      kind: "liquid",
      massKg: 0.8,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "liquid:water",
      revision: 1,
      kind: "liquid",
      massKg: 1,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-goggles_blue",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-goggles_up_orange",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-goggles_teal",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-nv_goggles",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-nv_goggles_strap",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-glasses_blue",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-glasses",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-balaclava",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-scarf_yellow",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-scarf_olive",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-earpiece_medic",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-headset_blue",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-headset_orange",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-earring_gold",
      revision: 1,
      kind: "inventory",
      massKg: 0.12,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-nurse-cap",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-clothing-civilian",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-clothing-civilian_f",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-clothing-captain",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-clothing-engineer",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-clothing-security",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-clothing-scientist",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-clothing-mechanic",
      revision: 1,
      kind: "inventory",
      massKg: 0.9,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-t0-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-t0-shoulders",
      revision: 1,
      kind: "inventory",
      massKg: 0.3,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-t0-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-medic-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-medic-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-medic-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-medic-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-medic-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-medic-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-pilot-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-pilot-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-pilot-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-pilot-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-pilot-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-pilot-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-marine-chest",
      revision: 1,
      kind: "inventory",
      massKg: 2.24,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-marine-legs",
      revision: 1,
      kind: "inventory",
      massKg: 1.36,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-marine-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.352,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-marine-boots",
      revision: 1,
      kind: "inventory",
      massKg: 1.04,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-marine-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 1.04,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-marine-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.92,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-salvage-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-salvage-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-salvage-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-salvage-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-salvage-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-salvage-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-recon-chest",
      revision: 1,
      kind: "inventory",
      massKg: 1.4,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-recon-legs",
      revision: 1,
      kind: "inventory",
      massKg: 0.85,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-recon-gloves",
      revision: 1,
      kind: "inventory",
      massKg: 0.22,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-recon-boots",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-recon-helmet",
      revision: 1,
      kind: "inventory",
      massKg: 0.65,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
    {
      id: "inventory:wardrobe-study-eva-recon-back",
      revision: 1,
      kind: "inventory",
      massKg: 1.2,
      centroid: [0, 0],
      inertiaKgM2: 0,
    },
  ];
