/**
 * Reference balance fits for the proposed component catalog. These are
 * balance sheets, not prefab ships: they exist so tests and
 * docs/ship_components.md can show that SM/MD/LG fits close their power,
 * heat, fuel, data and crew budgets with the catalog numbers. Prefab ship
 * designs (SHIPS-PREFABS) are authored separately and may reuse these.
 *
 * Frame: ship origin at the hull centre on the deck floor, +Y forward,
 * +X starboard, +Z up. Hardpoints sit on hull faces/roof; interior items on
 * the deck floor (z = 0).
 */
import type {
  ShipComponentFit,
  ShipComponentPlacement,
  ShipHardpoint,
  ShipSizeClass,
} from "./ship-components";

type Q = 0 | 1 | 2 | 3;
const hp = (
  id: string,
  socket: ShipHardpoint["socket"],
  sizeClass: ShipSizeClass,
  x: number,
  y: number,
  z: number,
  quarterTurns: Q = 0,
): ShipHardpoint => ({
  id,
  socket,
  sizeClass,
  position: [x, y, z],
  quarterTurns,
  reflected: false,
});
/** Faces: rear qt0 (outward -Y), starboard qt1 (+X), front qt2 (+Y), port qt3 (-X). */
const FACE = { rear: 0, starboard: 1, front: 2, port: 3 } as const;

function fit(
  id: string,
  name: string,
  hull: Omit<ShipComponentFit["hull"], "hardpoints">,
  mounts: readonly [ShipHardpoint, string][],
  interior: readonly [string, string, number, number, Q?][],
  notes: string,
): ShipComponentFit {
  const components: ShipComponentPlacement[] = [
    ...mounts.map(([h, componentId]) => ({
      id: `${componentId}@${h.id}`,
      componentId,
      position: h.position,
      quarterTurns: h.quarterTurns,
      reflected: h.reflected,
      hardpointId: h.id,
    })),
    ...interior.map(([placeId, componentId, x, y, q]) => ({
      id: placeId,
      componentId,
      position: [x, y, 0] as const,
      quarterTurns: (q ?? 0) as Q,
      reflected: false,
      hardpointId: null,
    })),
  ];
  return {
    id,
    name,
    status: "proposed",
    hull: { ...hull, hardpoints: mounts.map(([h]) => h) },
    components,
    notes,
  };
}

/** SM: 10 x 7 m single-seat fighter. */
export const REFERENCE_FIT_SM_FIGHTER: ShipComponentFit = fit(
  "balance.sm-fighter",
  "SM fighter balance fit",
  {
    id: "balance-hull-sm",
    sizeClass: "SM",
    massKg: 2600,
    lengthM: 10,
    beamM: 7,
    heightM: 2.2,
    decks: 1,
    passiveHeatRejectionKw: 15,
  },
  [
    [hp("rear-p", "rear", "SM", -1.2, -5, 1.1, FACE.rear), "thrust-block.sm"],
    [hp("rear-s", "rear", "SM", 1.2, -5, 1.1, FACE.rear), "thrust-block.sm"],
    [hp("rcs-fp", "face", "SM", -3.5, 2.5, 1.1, FACE.port), "rcs.sm"],
    [hp("rcs-fs", "face", "SM", 3.5, 2.5, 1.1, FACE.starboard), "rcs.sm"],
    [hp("rcs-ap", "face", "SM", -3.5, -2.5, 1.1, FACE.port), "rcs.sm"],
    [hp("rcs-as", "face", "SM", 3.5, -2.5, 1.1, FACE.starboard), "rcs.sm"],
    [hp("rcs-np", "face", "SM", -1.5, 5, 1.1, FACE.front), "rcs.sm"],
    [hp("rcs-ns", "face", "SM", 1.5, 5, 1.1, FACE.front), "rcs.sm"],
    [hp("gun-p", "top", "SM", -1.5, 2, 2.2), "autocannon.sm"],
    [hp("gun-s", "top", "SM", 1.5, 2, 2.2), "autocannon.sm"],
    [hp("nose", "top", "SM", 0, 3.5, 2.2), "laser-cannon.sm"],
    [hp("spine", "top", "SM", 0, 0, 2.2), "sensor-dish.sm"],
    [hp("shield", "top", "SM", 0, -1.5, 2.2), "shield-emitter.sm"],
    [hp("rad-p", "top", "SM", -1.5, -3, 2.2), "radiator.sm"],
    [hp("rad-s", "top", "SM", 1.5, -3, 2.2), "radiator.sm"],
    [hp("hatch", "top", "SM", 0, 1.5, 2.2), "hatch.exterior.sm"],
  ],
  [
    ["seat", "console.navigation.sm", 0, 2.5],
    ["core", "computer-core.sm", -1, 1.5],
    ["life", "life-support.sm", 1, 1.5],
    ["bunk", "crew-bunk.sm", 0, 0.5],
    ["reactor", "reactor.sm", 0, -2],
    ["battery", "battery.sm", -2, -1],
    ["tank", "fuel-tank.sm", 2, -1],
    ["pump", "coolant-pump.sm", -2, -3],
    ["sink", "heat-sink.sm", 2, -3],
    ["mag", "magazine.ballistic.sm", -2, 0.5],
    ["shieldgen", "shield-generator.sm", 2, 0.5],
  ],
  "Two thrust blocks for a high thrust-to-mass fighter. Combat heat exceeds two SM radiators; the heat sink buys minutes of combat, then the pilot must disengage or throttle.",
);

/** MD: 22 x 10 m corvette, the Wayfarer size band. */
export const REFERENCE_FIT_MD_CORVETTE: ShipComponentFit = fit(
  "balance.md-corvette",
  "MD corvette balance fit",
  {
    id: "balance-hull-md",
    sizeClass: "MD",
    massKg: 9000,
    lengthM: 22,
    beamM: 10,
    heightM: 3.5,
    decks: 1,
    passiveHeatRejectionKw: 30,
  },
  [
    [hp("rear-p", "rear", "MD", -2.5, -11, 1.75, FACE.rear), "ion-drive.md"],
    [hp("rear-s", "rear", "MD", 2.5, -11, 1.75, FACE.rear), "ion-drive.md"],
    [hp("rear-c", "rear", "SM", 0, -11, 1.75, FACE.rear), "ion-drive.sm"],
    [hp("rcs-fp", "face", "MD", -5, 6.5, 1.75, FACE.port), "rcs.md"],
    [hp("rcs-fs", "face", "MD", 5, 6.5, 1.75, FACE.starboard), "rcs.md"],
    [hp("rcs-ap", "face", "MD", -5, -6.5, 1.75, FACE.port), "rcs.md"],
    [hp("rcs-as", "face", "MD", 5, -6.5, 1.75, FACE.starboard), "rcs.md"],
    [hp("rcs-np", "face", "MD", -2, 11, 1.75, FACE.front), "rcs.md"],
    [hp("rcs-ns", "face", "MD", 2, 11, 1.75, FACE.front), "rcs.md"],
    [hp("retro-p", "face", "SM", -3.5, 11, 1.75, FACE.front), "thrust-block.sm"],
    [hp("retro-s", "face", "SM", 3.5, 11, 1.75, FACE.front), "thrust-block.sm"],
    [hp("turret-f", "top", "MD", 0, 6, 3.5), "autocannon.md"],
    [hp("turret-a", "top", "MD", 0, -3, 3.5), "laser-cannon.md"],
    [hp("pd-p", "top", "SM", -3.5, 3, 3.5), "point-defense.sm"],
    [hp("pd-s", "top", "SM", 3.5, 3, 3.5), "point-defense.sm"],
    [hp("pod", "top", "SM", 0, 9, 3.5), "missile-pod.sm"],
    [hp("dish", "top", "MD", -3, -7, 3.5), "sensor-dish.md"],
    [hp("mast", "top", "SM", 3.5, -8, 3.5), "scanner-mast.sm"],
    [hp("shield", "top", "MD", 0, 1.5, 3.5), "shield-emitter.md"],
    [hp("tractor", "bottom", "SM", 0, 4, 0), "tractor-projector.sm"],
    [hp("rad-p", "top", "MD", -3, -1, 3.5), "radiator.md"],
    [hp("rad-s", "top", "MD", 3, -1, 3.5), "radiator.md"],
    [hp("rad-a", "top", "SM", 3.5, -5, 3.5), "radiator.sm"],
    [hp("cargo", "edge", "MD", -5, -4, 0, FACE.port), "cargo-door.4m"],
    [hp("lock", "edge", "SM", 5, 2, 0, FACE.starboard), "airlock.exterior.md"],
  ],
  [
    ["helm", "console.navigation.sm", 0, 9.5],
    ["command", "console.command.sm", -1.5, 8.5],
    ["engineering", "console.engineering.sm", 2, -6],
    ["core", "computer-core.md", 1.5, 8.5],
    ["life", "life-support.md", -3, 5],
    ["filter", "air-filter.sm", -4, 3],
    ["oxygen", "oxygen-tank.sm", -4, 2],
    ["bunk-1", "crew-bunk.sm", 3, 5],
    ["bunk-2", "crew-bunk.sm", 3, 3.5],
    ["gravity", "gravity-unit.md", 0, 3],
    ["reactor", "reactor.md", 0, -7],
    ["battery", "battery.md", -3, -8],
    ["tank", "fuel-tank.md", 3, -9],
    ["pump", "coolant-pump.md", 3, -6],
    ["pump-aux", "coolant-pump.sm", 4, -6],
    ["sink", "heat-sink.md", 3, -4],
    ["mag", "magazine.ballistic.md", -3, 0],
    ["missiles", "magazine.missile.md", -3, 1],
    ["shieldgen", "shield-generator.md", 2.5, 0],
  ],
  "Wayfarer-sized multirole corvette: ion drives for endurance, one turret of each kind, PD cover, shields and a tractor.",
);

/** LG: 40 x 16 m two-deck frigate. */
export const REFERENCE_FIT_LG_FRIGATE: ShipComponentFit = fit(
  "balance.lg-frigate",
  "LG frigate balance fit",
  {
    id: "balance-hull-lg",
    sizeClass: "LG",
    massKg: 38000,
    lengthM: 40,
    beamM: 16,
    heightM: 7,
    decks: 2,
    passiveHeatRejectionKw: 60,
  },
  [
    [hp("rear-p", "rear", "XL", -4, -20, 3.5, FACE.rear), "ion-drive.xl"],
    [hp("rear-s", "rear", "XL", 4, -20, 3.5, FACE.rear), "ion-drive.xl"],
    [hp("pod-p", "rear", "MD", -7, -20, 3.5, FACE.rear), "thrust-block.md"],
    [hp("pod-s", "rear", "MD", 7, -20, 3.5, FACE.rear), "thrust-block.md"],
    ...([-12, -4, 4, 12] as const).flatMap((y, n) => [
      [hp(`rcs-p${n}`, "face", "MD", -8, y, 3.5, FACE.port), "rcs.md"] as [ShipHardpoint, string],
      [hp(`rcs-s${n}`, "face", "MD", 8, y, 3.5, FACE.starboard), "rcs.md"] as [ShipHardpoint, string],
    ]),
    [hp("rcs-np", "face", "MD", -3, 20, 3.5, FACE.front), "rcs.md"],
    [hp("rcs-ns", "face", "MD", 3, 20, 3.5, FACE.front), "rcs.md"],
    [hp("retro-p", "face", "MD", -5.5, 20, 3.5, FACE.front), "thrust-block.md"],
    [hp("retro-s", "face", "MD", 5.5, 20, 3.5, FACE.front), "thrust-block.md"],
    [hp("rail-f", "top", "LG", 0, 12, 7), "railgun.lg"],
    [hp("rail-a", "top", "LG", 0, -2, 7), "railgun.lg"],
    [hp("missile-p", "top", "MD", -5, 6, 7), "missile-pod.md"],
    [hp("missile-s", "top", "MD", 5, 6, 7), "missile-pod.md"],
    [hp("flak", "top", "MD", 0, 5, 7), "flak-cannon.md"],
    [hp("pd-p", "top", "MD", -6, -8, 7), "point-defense.md"],
    [hp("pd-s", "top", "MD", 6, -8, 7), "point-defense.md"],
    [hp("torpedo", "face", "MD", 0, 20, 2, FACE.front), "torpedo-launcher.md"],
    [hp("shield", "top", "LG", 0, 2, 7), "shield-emitter.lg"],
    [hp("radar", "top", "LG", 0, -9, 7), "radar-array.lg"],
    [hp("dish", "top", "MD", -5, 0, 7), "sensor-dish.md"],
    [hp("beacon", "top", "SM", 5, 0, 7), "relay-beacon.sm"],
    [hp("tractor", "bottom", "MD", 0, 6, 0), "tractor-projector.md"],
    [hp("drones", "bottom", "MD", 0, -6, 0), "drone-bay.md"],
    [hp("rad-p1", "top", "LG", -5, -14, 7), "radiator.lg"],
    [hp("rad-s1", "top", "LG", 5, -14, 7), "radiator.lg"],
    [hp("rad-p2", "top", "LG", -5, -4, 7), "radiator.lg"],
    [hp("rad-s2", "top", "LG", 5, -4, 7), "radiator.lg"],
    [hp("rad-p3", "top", "MD", -6, 12, 7), "radiator.md"],
    [hp("rad-s3", "top", "MD", 6, 12, 7), "radiator.md"],
    [hp("cargo", "edge", "LG", -8, -10, 0, FACE.port), "cargo-door.6m"],
    [hp("lock-p", "edge", "SM", -8, 8, 0, FACE.port), "airlock.exterior.md"],
    [hp("lock-s", "edge", "SM", 8, 8, 0, FACE.starboard), "airlock.exterior.md"],
    [hp("dock", "edge", "SM", 8, -10, 0, FACE.starboard), "docking-port.md"],
  ],
  [
    ["helm", "console.navigation.sm", 0, 18],
    ["command", "console.command.sm", -2, 17],
    ["gunnery", "console.fire-control.sm", 2, 17],
    ["sensors", "console.sensor.sm", -4, 16],
    ["engineering", "console.engineering.sm", 0, -12],
    ["core", "computer-core.lg", 4, 16],
    ["life", "life-support.lg", -5, 10],
    ["filter", "air-filter.md", -6, 8],
    ["oxygen", "oxygen-tank.md", -6, 6],
    ["bunk-1", "crew-bunk.sm", 5, 10],
    ["bunk-2", "crew-bunk.sm", 5, 9],
    ["bunk-3", "crew-bunk.sm", 5, 8],
    ["bunk-4", "crew-bunk.sm", 5, 7],
    ["gravity", "gravity-unit.lg", 0, 8],
    ["reactor-main", "reactor.lg", 0, -15],
    ["reactor-aux", "reactor.md", -5, -12],
    ["battery", "battery.lg", 5, -12],
    ["capacitor", "capacitor.lg", 3, 0],
    ["tank-main", "fuel-tank.lg", -4, -17],
    ["tank-aux", "fuel-tank.md", 4, -17],
    ["pump-main", "coolant-pump.lg", -6, -15],
    ["pump-aux", "coolant-pump.lg", 6, -15],
    ["sink", "heat-sink.md", 6, -5],
    ["mag", "magazine.ballistic.md", -3, 0],
    ["missiles", "magazine.missile.lg", -3, 3],
    ["torpedoes", "magazine.torpedo.lg", 0, 14],
    ["shieldgen", "shield-generator.lg", 0, 0],
  ],
  "Line frigate: two rear-only XL ion drives plus MD thrust blocks, two railguns on one capacitor bank, missiles, flak, PD, a manual torpedo tube and a drone bay. Combat runs on the battery for a bounded time by design.",
);

export const SHIP_COMPONENT_REFERENCE_FITS: readonly ShipComponentFit[] = [
  REFERENCE_FIT_SM_FIGHTER,
  REFERENCE_FIT_MD_CORVETTE,
  REFERENCE_FIT_LG_FRIGATE,
];
