/** Shared production actor-view baseline for the browser and replication harness.
 * World admission and spatial scopes remain owned by bindSharedWorld. */
export const GAME_VIEW_KEYS = [
  "ownGameShipAccess",
  "ownConstructionInstances",
  "ownConstructionDecks",
  "ownConstructionLocation",
  "ownConstructionSeat",
  "ownAuthoredFlights",
  "ownAuthoredFlightFittings",
  "ownAuthoredFlightPhysics",
  "ownAuthoredFlightActuators",
  "ownAuthoredFlightPowerFittings",
  "ownPassengerGrants",
  "ownPassengerVisit",
  "currentPassengerInterior",
  "currentInteriorCrew",
  "visibleCrewPresentation",
  "ownEvaBody",
  "ownEvaAirlockCycle",
  "visibleEvaBodies",
  "visibleShipLogic",
  "ownEvaSuit",
  "visibleActuatorExhaust",
  "visibleCombatActions",
  "ownConstructionDoors",
  "ownConstructionNativePressure",
  "ownNativeAirlocks",
  "ownConstructionTraversals",
  "ownConstructionTraversalLinks",
  "ownConstructionStairWalks",
  "ownConstructionStairEgressGeometry",
  "ownIdentityLinks",
  "ownAppearance",
  "ownCharacters",
  "ownShips",
  "ownStations",
  "ownEditReceipts",
  "ownSpaceBodies",
  "admittedSystemScapes",
  "ownShipZones",
  "nearbyFieldAsteroids",
  "ownActuatorOutputs",
  "ownInteractions",
  "ownCombat",
  "ownCombatImpact",
  "ownCharacterVitals",
  "ownShipComponentDamage",
  "ownShipPower",
  "ownGroundItems",
  "ownInventoryState",
  "ownInventoryItems",
  "ownInventoryContainers",
  "ownInventoryHotbar",
  "ownReachableCargoContainers",
  "ownReachableCargoItems",
  "ownCarriedInventoryRevisions",
  "publishedItemDefinitions",
  "ownItemDefinitionPins",
  "componentCatalogSnapshots",
] as const;

export function gameViewKeys(constructionReview = false) {
  const keys: ((typeof GAME_VIEW_KEYS)[number] | "ownConstructionGrants")[] = [
    ...GAME_VIEW_KEYS,
  ];
  if (constructionReview)
    keys.splice(keys.indexOf("ownIdentityLinks"), 0, "ownConstructionGrants");
  return keys;
}
