import {expect,test,vi} from 'vitest';
import {Identity} from 'spacetimedb';
vi.mock('spacetimedb/server',()=>({SenderError:class extends Error{},Range:class {constructor(public from:any,public to:any){}},t:new Proxy({},{get:()=>()=>({})})}));
vi.mock('./auth',()=>({requireGame:(ctx:any)=>{if(!ctx.testAuthenticated)throw Error('unauthenticated');return {kind:ctx.testKind??'oidc'};}}));
import {setGrant,saveDraft,publishBlueprint,ownDrafts,ownBlueprints,expireGrants} from './construction';
import {emptyLayout,SHAPE_REVISION} from '../../content/src/ship-layout';
import {CONSTRUCTION_SCHEMA,CONSTRUCTION_COMPILER} from '../../content/src/construction';
import {PINNED_FLOOR_KIT,FLOOR_KIT_HASH} from '../../sim/src/construction-transactions';
function table(indexes:Record<string,string>={}){const rows:any[]=[];const result:any={rows,insert:(r:any)=>{if(rows.some(x=>x.id===r.id))throw Error('duplicate primary key');rows.push(r);return r;},id:{find:(id:string)=>rows.find(r=>r.id===id),update:(r:any)=>{const i=rows.findIndex(x=>x.id===r.id);if(i<0)throw Error('missing');rows[i]=r;}}};for(const [name,column] of Object.entries(indexes))result[name]={filter:(v:any)=>rows.filter(r=>v?.to?r[column]<=v.to.value:String(r[column])===String(v))};return result;}
function fixture(){let serial=0;const alice=Identity.fromString('1'.repeat(64)),bob=Identity.fromString('2'.repeat(64));const db:any={constructionGrant:table({by_principal:'principal',by_expiry:'nextCheckMicros'}),constructionDraft:table({by_workspace:'workspaceId'}),constructionBlueprint:table({by_workspace:'workspaceId',by_draft:'draftId'}),constructionReceipt:table({by_principal:'principal'})};const a:any={db,sender:alice,testAuthenticated:true,senderAuth:{jwt:{fullPayload:{realm_access:{roles:['sidereal-construction-admin']}}}},timestamp:{microsSinceUnixEpoch:10n},newUuidV4:()=>({toString:()=>`server-${++serial}`})};const b:any={...a,sender:bob,senderAuth:{jwt:{fullPayload:{}}}};const grant=(principal=alice,capability='draft.write')=>setGrant(a,{principal:principal.toHexString(),workspaceId:'w',capability,expiresMicros:100n,revoked:false,expectedRevision:0n,operationId:'grant-'+principal.toHexString().slice(0,4)+'-'+capability});return {a,b,db,alice,bob,grant};}
function doc(){const layout=emptyLayout('design','deck');layout.tiles=[{id:'floor',deckId:'deck',shape:'rectangle',revision:SHAPE_REVISION,vertices:[[0,0],[64,0],[64,64],[0,64]],material:'deck'}];return {schema:CONSTRUCTION_SCHEMA,compiler:CONSTRUCTION_COMPILER,layout,floorKit:{id:PINNED_FLOOR_KIT.id,revision:PINNED_FLOOR_KIT.revision,sha256:FLOOR_KIT_HASH},floors:[{id:'floor',deckId:'deck',partId:'square-2m',origin:[0,0,0],quarterTurns:0,reflected:false}]};}
test('explicit provider admin grants authoring; ordinary players cannot self-grant',()=>{const f=fixture();expect(()=>setGrant(f.b,{principal:f.bob.toHexString(),workspaceId:'w',capability:'grant.manage',expiresMicros:100n,revoked:false,expectedRevision:0n,operationId:'self'})).toThrow('grant');f.grant();expect(f.db.constructionGrant.rows).toHaveLength(1);f.a.testKind='development';expect(()=>f.grant(f.bob)).toThrow('grant');});
test('save and publish remain separate, private, CAS checked and immutable',()=>{const f=fixture();for(const cap of ['draft.read','draft.write','blueprint.publish'])f.grant(f.alice,cap);
 const args={workspaceId:'w',draftId:'draft',documentJson:JSON.stringify(doc()),expectedRevision:0n,operationId:'save'};saveDraft(f.a,args);saveDraft(f.a,args);expect(f.db.constructionDraft.rows[0].revision).toBe(1n);expect(ownDrafts(f.b)).toEqual([]);expect(()=>saveDraft(f.b,args)).toThrow('grant');
 const pub={workspaceId:'w',draftId:'draft',expectedRevision:1n,operationId:'publish'};publishBlueprint(f.a,pub);publishBlueprint(f.a,pub);expect(f.db.constructionBlueprint.rows).toHaveLength(1);const original=JSON.stringify(ownBlueprints(f.a),(_,v)=>typeof v==='bigint'?String(v):v);
 const changed=doc();changed.layout.name='Changed later';saveDraft(f.a,{...args,documentJson:JSON.stringify(changed),expectedRevision:1n,operationId:'save2'});expect(JSON.stringify(ownBlueprints(f.a),(_,v)=>typeof v==='bigint'?String(v):v)).toBe(original);expect(()=>publishBlueprint(f.a,{...pub,operationId:'stale'})).toThrow('revision');expect(ownBlueprints(f.b)).toEqual([]);
});
test('an incomplete valid-schema draft is recoverable but cannot publish as native structure',()=>{const f=fixture();for(const cap of ['draft.read','draft.write','blueprint.publish'])f.grant(f.alice,cap);const d=doc();d.floors=[];saveDraft(f.a,{workspaceId:'w',draftId:'draft',documentJson:JSON.stringify(d),expectedRevision:0n,operationId:'save'});expect(ownDrafts(f.a)).toHaveLength(1);expect(()=>publishBlueprint(f.a,{workspaceId:'w',draftId:'draft',expectedRevision:1n,operationId:'pub'})).toThrow('binding');expect(f.db.constructionBlueprint.rows).toEqual([]);});
test('expiry removes private projection and denies replay; expired grants leave expiry scan',()=>{const f=fixture();for(const cap of ['draft.read','draft.write'])f.grant(f.alice,cap);const args={workspaceId:'w',draftId:'draft',documentJson:JSON.stringify(doc()),expectedRevision:0n,operationId:'save'};saveDraft(f.a,args);f.a.timestamp.microsSinceUnixEpoch=100n;expect(()=>saveDraft(f.a,args)).toThrow('grant');expireGrants(f.a);expect(ownDrafts(f.a)).toEqual([]);expect(f.db.constructionGrant.rows.every((g:any)=>g.revoked&&g.revision===2n&&g.nextCheckMicros>100n)).toBe(true);});
