/** Aurelian Synod (alien): lavender, violet and gold; rounded bows, crescent wings, crystal decorators. */
import { arcTile, door, edge, face, module, opening, polygonTiles, prefab, rectTiles, room, top, volume } from "./builders";

/** Starter candidate: round-nosed seedling scout with twin crescent fins. */
export const AU_LUMEN = prefab({
  id: "au.s.lumen",
  name: "Lumen",
  description: "Aurelian seedling scout: a round crystal-lit bridge, garden hold and resonance drives. Starter candidate.",
  faction: "Aurelian Synod",
  role: "Scout",
  theme: "aurelian",
  sizeClass: "S",
  volumes: [
    volume("hull", "hull", "deck", [...rectTiles(0, 0, 8, 6), arcTile(8, 3, 3, "ne"), arcTile(8, 0, 3, "se")], { logo: true }),
    volume("fin-p", "plate", "wing", [...rectTiles(0, 6, 2, 8), arcTile(2, 6, 2, "ne")]),
    volume("fin-s", "plate", "wing", [...rectTiles(0, -2, 2, 0), arcTile(2, -2, 2, "se")]),
  ],
  rooms: [
    room("engine", "RESONATOR", "engineering", [0, 0, 3, 6]),
    room("garden", "GARDEN", "hydro", [3, 0, 8, 3]),
    room("sanctum", "SANCTUM", "lounge", [3, 3, 8, 6]),
    room("bridge", "CROWN", "bridge", [8, 0, 11, 6]),
  ],
  edges: [
    door("d-engine", [3, 1], [3, 3], "door.forcefield"),
    door("d-sanctum", [4, 3], [6, 3], "door.sliding"),
    door("d-bridge", [8, 3], [8, 5], "door.forcefield"),
    edge("g-bridge", [8, 0], [8, 3], "wall.glazed"),
  ],
  mounts: [
    face("drive-s", "resonance-drive.aurelian.md", "aft", [0, 1.5]),
    face("drive-p", "resonance-drive.aurelian.md", "aft", [0, 4.5]),
    opening("airlock", "airlock.exterior.md", "starboard", [6, 0]),
    top("plasma", "plasma-turret.md", [4, 2]),
    top("lance", "laser-cannon.sm", [9, 2.5]),
    top("ward", "shield-emitter.sm", [1, 4.5]),
    top("rad-a", "radiator.md", [1, 1]),
    top("rad-b", "radiator.md", [6, 4]),
    module("helm", "console.navigation.sm", [9, 2.5], "fore"),
    module("core", "computer-core.sm", [8, 1], "port"),
    module("reactor", "reactor.md", [0, 1.5], "fore"),
    module("life", "life-support.sm", [0.5, 5], "fore"),
    module("bunk", "crew-bunk.sm", [4.5, 4.5], "starboard"),
    module("garden", "hydroponics.sm", [5, 0.5], "port"),
  ],
  markings: { name: "LUMEN", number: "AS-03", emblem: "crystal" },
});

/** Medium: the prototype Crescent explorer, round bow and crescent wings. */
export const AU_CRESCENT = prefab({
  id: "au.m.crescent",
  name: "Crescent",
  description: "Aurelian explorer: semicircular crown bridge, crescent wings with point defence, twin large resonance drives.",
  faction: "Aurelian Synod",
  role: "Explorer",
  theme: "aurelian",
  sizeClass: "M",
  volumes: [
    volume(
      "hull",
      "hull",
      "deck",
      [
        ...rectTiles(1, 0, 14, 8),
        ...rectTiles(0, 1, 1, 7),
        arcTile(0, 0, 1, "sw"),
        arcTile(0, 7, 1, "nw"),
        arcTile(14, 4, 4, "ne"),
        arcTile(14, 0, 4, "se"),
      ],
      { spine: true },
    ),
    volume("wing-p", "plate", "wing", [...rectTiles(4, 8, 10, 10), arcTile(10, 8, 2, "ne"), arcTile(2, 8, 2, "nw")]),
    volume("wing-s", "plate", "wing", [...rectTiles(4, -2, 10, 0), arcTile(10, -2, 2, "se"), arcTile(2, -2, 2, "sw")]),
  ],
  rooms: [
    room("eng", "RESONATOR", "engineering", [0, 0, 4, 8]),
    room("hall", "NAVE", "corridor", [4, 3, 14, 5]),
    room("garden", "GARDEN", "hydro", [4, 0, 9, 3]),
    room("med", "HEALING", "medbay", [9, 0, 14, 3]),
    room("cells", "CELLS", "quarters", [4, 5, 9, 8]),
    room("choir", "CHOIR", "lounge", [9, 5, 14, 8]),
    room("bridge", "CROWN", "bridge", [14, 0, 18, 8]),
  ],
  edges: [
    door("d-eng", [4, 3], [4, 5], "door.forcefield"),
    door("d-garden", [5, 3], [7, 3], "door.sliding"),
    door("d-med", [10, 3], [12, 3], "door.sliding"),
    door("d-cells", [5, 5], [7, 5]),
    door("d-choir", [10, 5], [12, 5], "door.sliding"),
    door("d-bridge", [14, 3], [14, 5], "door.forcefield"),
    edge("g-bridge-s", [14, 0], [14, 3], "wall.glazed"),
    edge("g-bridge-p", [14, 5], [14, 8], "wall.glazed"),
  ],
  mounts: [
    face("drive-s", "resonance-drive.aurelian.lg", "aft", [0, 2.5]),
    face("drive-p", "resonance-drive.aurelian.lg", "aft", [0, 5.5]),
    opening("lock", "airlock.exterior.md", "starboard", [13, 0]),
    top("plasma", "plasma-turret.md", [5, 1]),
    top("lance", "laser-cannon.md", [10, 5]),
    top("ward", "shield-emitter.md", [15, 3]),
    top("dish", "sensor-dish.md", [2, 5]),
    top("pd-p", "point-defense.sm", [6, 8.5]),
    top("pd-s", "point-defense.sm", [6, -1.5]),
    top("rad-lg", "radiator.lg", [1, 1.5]),
    top("rad-md", "radiator.md", [7, 5]),
    top("rad-md-2", "radiator.md", [11, 1]),
    module("helm", "console.navigation.sm", [16, 3.5], "fore"),
    module("core", "computer-core.md", [14, 2], "port"),
    module("reactor", "reactor.lg", [0, 2], "fore"),
    module("life", "life-support.md", [1, 0], "fore"),
    module("bunk-1", "crew-bunk.sm", [4.5, 6.5], "starboard"),
    module("bunk-2", "crew-bunk.sm", [6.5, 6.5], "starboard"),
    module("garden-1", "hydroponics.sm", [4.5, 0.5], "port"),
    module("garden-2", "hydroponics.sm", [6.5, 0.5], "port"),
  ],
  markings: { name: "CRESCENT", number: "AS-07", emblem: "crystal" },
});

/** Large: cathedral cruiser with a round crown bow, crystal spire and four resonance drives. */
export const AU_CATHEDRAL = prefab({
  id: "au.l.cathedral",
  name: "Cathedral",
  description: "Aurelian cruiser: long nave, round crown bridge with a crystal spire, crescent wings and paired plasma turrets.",
  faction: "Aurelian Synod",
  role: "Cruiser",
  theme: "aurelian",
  sizeClass: "L",
  volumes: [
    volume("hull", "hull", "deck", [...rectTiles(0, 0, 28, 12), ...rectTiles(28, 4, 32, 8), arcTile(28, 8, 4, "ne"), arcTile(28, 0, 4, "se")], { spine: true }),
    volume("spire", "plate", "plate", polygonTiles([[32, 5], [34, 6], [32, 7]])),
    volume("wing-p", "plate", "wing", [...rectTiles(8, 12, 20, 14), arcTile(20, 12, 2, "ne"), arcTile(6, 12, 2, "nw")]),
    volume("wing-s", "plate", "wing", [...rectTiles(8, -2, 20, 0), arcTile(20, -2, 2, "se"), arcTile(6, -2, 2, "sw")]),
  ],
  rooms: [
    room("eng", "RESONATORS", "engineering", [0, 0, 5, 12]),
    room("hall", "NAVE", "corridor", [5, 5, 28, 7]),
    room("garden", "GARDEN", "hydro", [5, 0, 10, 5]),
    room("med", "HEALING", "medbay", [10, 0, 15, 5]),
    room("shop", "FORGE", "workshop", [15, 0, 20, 5]),
    room("cargo", "RELIQUARY", "cargo", [20, 0, 24, 5]),
    room("lock", "AIRLOCK", "airlock", [24, 0, 28, 5]),
    room("q1", "CELLS", "quarters", [5, 7, 9, 12]),
    room("q2", "CELLS", "quarters", [9, 7, 13, 12]),
    room("galley", "REFECTORY", "galley", [13, 7, 17, 12]),
    room("choir", "CHOIR", "lounge", [17, 7, 23, 12]),
    room("ward", "WARD", "armory", [23, 7, 28, 12]),
    room("bridge", "CROWN", "bridge", [28, 0, 32, 12]),
  ],
  edges: [
    door("d-eng", [5, 5], [5, 7], "door.forcefield"),
    door("d-garden", [6, 5], [8, 5], "door.sliding"),
    door("d-med", [11, 5], [13, 5], "door.sliding"),
    door("d-shop", [16, 5], [18, 5]),
    door("d-cargo", [21, 5], [23, 5]),
    door("d-lock", [25, 5], [27, 5], "door.airlock"),
    door("d-q1", [6, 7], [8, 7]),
    door("d-q2", [10, 7], [12, 7]),
    door("d-galley", [14, 7], [16, 7], "door.sliding"),
    door("d-choir", [19, 7], [21, 7], "door.sliding"),
    door("d-ward", [24, 7], [26, 7], "door.blast"),
    door("d-bridge", [28, 5], [28, 7], "door.forcefield"),
    edge("g-choir", [21, 7], [23, 7], "wall.glazed"),
    edge("g-bridge-s", [28, 0], [28, 5], "wall.glazed"),
    edge("g-bridge-p", [28, 7], [28, 12], "wall.glazed"),
  ],
  mounts: [
    face("drive-1", "resonance-drive.aurelian.lg", "aft", [0, 1.5]),
    face("drive-2", "resonance-drive.aurelian.lg", "aft", [0, 4.5]),
    face("drive-3", "resonance-drive.aurelian.lg", "aft", [0, 7.5]),
    face("drive-4", "resonance-drive.aurelian.lg", "aft", [0, 10.5]),
    opening("lock", "airlock.exterior.md", "starboard", [25, 0]),
    top("plasma-s", "plasma-turret.lg", [6, 1]),
    top("plasma-p", "plasma-turret.lg", [6, 8]),
    top("lance-s", "laser-cannon.md", [21, 1]),
    top("lance-p", "laser-cannon.md", [21, 9]),
    top("ward", "shield-emitter.lg", [14, 4.5]),
    top("dish", "sensor-dish.lg", [28.5, 4.5]),
    top("beacon", "relay-beacon.md", [25, 2]),
    top("pd-p", "point-defense.md", [12, 12]),
    top("pd-s", "point-defense.md", [12, -2]),
    top("rad-1", "radiator.lg", [1, 1]),
    top("rad-2", "radiator.lg", [1, 8]),
    top("rad-3", "radiator.lg", [16, 9]),
    top("rad-4", "radiator.lg", [11, 8]),
    top("rad-5", "radiator.md", [11, 1]),
    module("helm", "console.navigation.sm", [30, 5.5], "fore"),
    module("command", "console.command.sm", [29, 8], "fore"),
    module("fire", "console.fire-control.sm", [29, 3], "fore"),
    module("core", "computer-core.lg", [28, 2], "port"),
    module("reactor-1", "reactor.lg", [0.5, 0.5], "fore"),
    module("reactor-2", "reactor.lg", [0.5, 7.5], "fore"),
    module("life", "life-support.lg", [1.5, 5], "fore"),
    module("shieldgen", "shield-generator.lg", [24, 8], "fore"),
    module("bunk-1", "crew-bunk.sm", [5.5, 10.5], "starboard"),
    module("bunk-2", "crew-bunk.sm", [5.5, 8.5], "starboard"),
    module("bunk-3", "crew-bunk.sm", [9.5, 10.5], "starboard"),
    module("bunk-4", "crew-bunk.sm", [9.5, 8.5], "starboard"),
    module("garden-1", "hydroponics.sm", [5.5, 0.5], "port"),
    module("garden-2", "hydroponics.sm", [7.5, 0.5], "port"),
  ],
  markings: { name: "CATHEDRAL", number: "AS-01", emblem: "crystal" },
});
