/** Frontier industrial and Vitreous Choir crystalline designs. */
import { door, edge, face, module, opening, polygonTiles, prefab, room, top, volume } from "./builders";

/** Medium industrial: boxy hauler with ore bins, cab, mining lasers and salvage arms. */
export const IND_MULE = prefab({
  id: "ind.m.mule",
  name: "Mule",
  description: "Frontier mining hauler: forward cab, twin ore bins, 4 m cargo door, mining lasers and salvage arms.",
  faction: "Frontier Guilds",
  role: "Mining hauler",
  theme: "industrial",
  sizeClass: "M",
  volumes: [
    volume("hull", "hull", "deck", polygonTiles([[0, 0], [20, 0], [20, 2], [23, 2], [25, 4], [25, 6], [23, 8], [20, 8], [20, 10], [0, 10]]), { spine: true }),
    volume("bin-s", "hull", "pod", polygonTiles([[3, -3], [13, -3], [13, 0], [3, 0]]), { logo: false }),
    volume("bin-p", "hull", "pod", polygonTiles([[3, 10], [12, 10], [12, 13], [3, 13]]), { logo: false }),
  ],
  rooms: [
    room("eng", "ENGINES", "engineering", [0, 0, 4, 10]),
    room("hall", "SPINE", "corridor", [4, 4, 20, 6]),
    room("ore", "ORE BAY", "cargo", [4, 0, 10, 4]),
    room("shop", "WORKSHOP", "workshop", [10, 0, 14, 4]),
    room("bay", "CARGO BAY", "cargo", [14, 0, 20, 4]),
    room("bunks", "BUNKS", "quarters", [4, 6, 9, 10]),
    room("galley", "GALLEY", "galley", [9, 6, 13, 10]),
    room("lock", "AIRLOCK", "airlock", [13, 6, 17, 10]),
    room("lounge", "BREAK ROOM", "lounge", [17, 6, 20, 10]),
    room("cab", "CAB", "bridge", [20, 2, 25, 8]),
  ],
  edges: [
    door("d-eng", [4, 4], [4, 6], "door.blast"),
    door("d-ore", [6, 4], [8, 4], "door.blast"),
    door("d-shop", [11, 4], [13, 4]),
    door("d-bay", [16, 4], [18, 4], "door.blast"),
    door("d-bunks", [5, 6], [7, 6]),
    door("d-galley", [10, 6], [12, 6], "door.sliding"),
    door("d-lock", [14, 6], [16, 6], "door.airlock"),
    door("d-lounge", [18, 6], [20, 6]),
    door("d-cab", [20, 4], [20, 6], "door.sliding"),
    edge("h-bay", [14, 0], [14, 4], "wall.half"),
  ],
  mounts: [
    face("rcs-bow-p", "rcs.sm", "port", [22.5, 8]),
    face("rcs-bow-s", "rcs.sm", "starboard", [22.5, 2]),
    face("rcs-stern-p", "rcs.sm", "port", [0.5, 10]),
    face("rcs-stern-s", "rcs.sm", "starboard", [0.5, 0]),
    face("block-s", "thrust-block.lg", "aft", [0, 1.5]),
    face("block-p", "thrust-block.lg", "aft", [0, 8.5]),
    face("block-c", "thrust-block.md", "aft", [0, 5]),
    face("arm-s", "salvage-arm.md", "fore", [20, 1]),
    face("arm-p", "salvage-arm.md", "fore", [20, 9]),
    opening("cargo-door", "cargo-door.4m", "starboard", [17, 0]),
    opening("lock", "airlock.exterior.md", "port", [15, 10]),
    top("drill-a", "mining-laser.md", [21, 3]),
    top("drill-b", "mining-laser.md", [21, 5]),
    top("tractor", "tractor-projector.md", [16, 6.5]),
    top("clamp", "docking-clamp.md", [12, 6]),
    top("pd", "point-defense.sm", [10, 1]),
    top("dish", "sensor-dish.sm", [23, 4.5]),
    top("rad-s", "radiator.lg", [5, -3]),
    top("rad-p", "radiator.lg", [5, 10]),
    top("rad-c", "radiator.md", [1, 4]),
    module("helm", "console.navigation.sm", [23, 4.5], "fore"),
    module("core", "computer-core.md", [20, 2], "port"),
    module("reactor", "reactor.md", [0.5, 0.5], "fore"),
    module("life", "life-support.md", [0.5, 6], "fore"),
    module("fuel", "fuel-tank.md", [2, 7], "fore"),
    module("bunk-1", "crew-bunk.sm", [4.5, 8.5], "starboard"),
    module("bunk-2", "crew-bunk.sm", [4.5, 6.5], "starboard"),
  ],
  markings: { name: "MULE", number: "FG-208", emblem: "gear" },
});

/** Medium crystalline alien: faceted shard hull with 1:2 crystal spikes. */
export const CRY_SHARD = prefab({
  id: "cry.m.shard",
  name: "Shard",
  description: "Vitreous Choir envoy: faceted crystal hull, twin spike wings, resonance drives and a singing lance.",
  faction: "Vitreous Choir",
  role: "Envoy",
  theme: "crystalline",
  sizeClass: "M",
  volumes: [
    volume("hull", "hull", "deck", polygonTiles([[0, 2], [2, 0], [14, 0], [22, 4], [14, 8], [2, 8], [0, 6]]), { spine: true }),
    volume("spike-p", "plate", "wing", polygonTiles([[4, 8], [12, 8], [6, 11], [4, 11]])),
    volume("spike-s", "plate", "wing", polygonTiles([[4, -3], [6, -3], [12, 0], [4, 0]])),
  ],
  rooms: [
    room("eng", "RESONANCE", "engineering", [0, 0, 4, 8]),
    room("hall", "PRISM", "corridor", [4, 3, 14, 5]),
    room("garden", "LATTICE", "hydro", [4, 0, 9, 3]),
    room("med", "MENDING", "medbay", [9, 0, 14, 3]),
    room("cells", "FACETS", "quarters", [4, 5, 9, 8]),
    room("choir", "CHOIR", "lounge", [9, 5, 14, 8]),
    room("bridge", "APEX", "bridge", [14, 0, 22, 8]),
  ],
  edges: [
    door("d-eng", [4, 3], [4, 5], "door.forcefield"),
    door("d-garden", [5, 3], [7, 3], "door.forcefield"),
    door("d-med", [10, 3], [12, 3], "door.forcefield"),
    door("d-cells", [5, 5], [7, 5], "door.forcefield"),
    door("d-choir", [10, 5], [12, 5], "door.forcefield"),
    door("d-bridge", [14, 3], [14, 5], "door.forcefield"),
    edge("g-bridge-s", [14, 0], [14, 3], "wall.glazed"),
    edge("g-bridge-p", [14, 5], [14, 8], "wall.glazed"),
  ],
  mounts: [
    face("rcs-bow-p", "rcs.sm", "port", [13.5, 8]),
    face("rcs-bow-s", "rcs.sm", "starboard", [11.5, 0]),
    face("rcs-stern-p", "rcs.sm", "port", [2.5, 8]),
    face("rcs-stern-s", "rcs.sm", "starboard", [2.5, 0]),
    face("drive-s", "resonance-drive.aurelian.md", "aft", [0, 3]),
    face("drive-p", "resonance-drive.aurelian.md", "aft", [0, 5]),
    face("spike-drive-p", "resonance-drive.aurelian.sm", "aft", [4, 9.5]),
    face("spike-drive-s", "resonance-drive.aurelian.sm", "aft", [4, -1.5]),
    opening("lock", "airlock.exterior.md", "starboard", [13, 0]),
    top("lance", "laser-cannon.md", [5, 1]),
    top("plasma", "plasma-turret.md", [10, 5]),
    top("ward", "shield-emitter.md", [15, 3]),
    top("beacon", "relay-beacon.sm", [3, 3]),
    top("drill", "mining-laser.sm", [6, 9]),
    top("rad-a", "radiator.md", [1, 3]),
    top("rad-b", "radiator.md", [6, 5]),
    top("rad-c", "radiator.lg", [10, 1]),
    module("helm", "console.navigation.sm", [18, 3.5], "fore"),
    module("core", "computer-core.md", [15, 1], "port"),
    module("reactor", "reactor.lg", [0, 2], "fore"),
    module("life", "life-support.sm", [2, 0.5], "fore"),
    module("bunk-1", "crew-bunk.sm", [4.5, 6.5], "starboard"),
    module("bunk-2", "crew-bunk.sm", [6.5, 6.5], "starboard"),
  ],
  markings: { name: "SHARD", number: "VC-12", emblem: "crystal" },
});
