/** Riftjack pirates: rusted brown, black, blood red and hazard yellow; asymmetric, mismatched fits. */
import { door, edge, face, module, opening, polygonTiles, prefab, room, top, volume } from "./builders";

/** Starter candidate: a lopsided salvage cutter with a mismatched engine pair. */
export const RJ_JACKAL = prefab({
  id: "rj.s.jackal",
  name: "Jackal",
  description: "Riftjack salvage cutter: lopsided nose, bolted-on side pod, salvaged ion drive beside a thrust block. Starter candidate.",
  faction: "Riftjack",
  role: "Cutter",
  theme: "riftjack",
  sizeClass: "S",
  volumes: [
    volume("hull", "hull", "deck", polygonTiles([[0, 0], [8, 0], [11, 3], [11, 4], [7, 6], [0, 6]]), { logo: true }),
    volume("pod-s", "hull", "cabin", polygonTiles([[0, -2], [4, -2], [4, 0], [0, 0]]), { logo: false }),
    volume("armour-p", "plate", "plate", polygonTiles([[1, 6], [6, 6], [6, 7], [1, 7]])),
  ],
  rooms: [
    room("engine", "ENGINE", "engineering", [0, 0, 3, 6]),
    room("hold", "HOLD", "cargo", [3, 0, 7, 3]),
    room("bunk", "BUNK", "quarters", [3, 3, 7, 6]),
    room("bridge", "BRIDGE", "bridge", [7, 0, 11, 6]),
  ],
  edges: [
    door("d-engine", [3, 1], [3, 3], "door.blast"),
    door("d-bunk", [4, 3], [6, 3]),
    door("d-bridge", [7, 3], [7, 5], "door.sliding"),
    edge("h-hold", [7, 0], [7, 3], "wall.half"),
  ],
  mounts: [
    face("rcs-bow-p", "rcs.sm", "port", [5.5, 6]),
    face("rcs-bow-s", "rcs.sm", "starboard", [7.5, 0]),
    face("salvage-drive", "ion-drive.salvaged.md", "aft", [0, 1.5]),
    face("block", "thrust-block.md", "aft", [0, 4.5]),
    face("pod-block", "thrust-block.sm", "aft", [0, -1]),
    face("gun-p", "side-cannon.sm", "port", [6.5, 6]),
    opening("airlock", "airlock.exterior.md", "starboard", [5, 0]),
    top("turret", "autocannon.md", [4, 1]),
    top("flak", "flak-cannon.sm", [8, 2]),
    top("clamp", "docking-clamp.md", [1, -2]),
    top("rad-a", "radiator.md", [1, 3]),
    top("rad-b", "radiator.md", [1, 1]),
    module("helm", "console.navigation.sm", [9, 2.5], "fore"),
    module("core", "computer-core.sm", [8, 1], "port"),
    module("reactor", "reactor.md", [0, 0], "fore"),
    module("life", "life-support.sm", [0.5, 4.5], "fore"),
    module("bunk", "crew-bunk.sm", [3.5, 4.5], "starboard"),
    module("ammo", "magazine.ballistic.sm", [5.5, 0.5], "port"),
  ],
  markings: { name: "JACKAL", number: "RJ-13", emblem: "skull" },
});

/** Medium: the prototype Marauder raider, asymmetric port pod and nose ram. */
export const RJ_MARAUDER = prefab({
  id: "rj.m.marauder",
  name: "Marauder",
  description: "Riftjack raider: armoured port pod, nose ram, salvaged drives and a heavy dorsal autocannon.",
  faction: "Riftjack",
  role: "Raider",
  theme: "riftjack",
  sizeClass: "M",
  volumes: [
    volume("hull", "hull", "deck", polygonTiles([[0, 0], [18, 0], [22, 2], [22, 6], [18, 8], [0, 8]]), { spine: true }),
    volume("pod-p", "hull", "pod", polygonTiles([[4, 8], [15, 8], [12, 11], [4, 11]]), { logo: false }),
    volume("plate-s", "plate", "wing", polygonTiles([[6, -2], [10, -2], [12, 0], [6, 0]])),
    volume("ram", "plate", "plate", polygonTiles([[22, 3], [24, 4], [22, 5]])),
  ],
  rooms: [
    room("eng", "ENGINE", "engineering", [0, 0, 4, 8]),
    room("hall", "GANGWAY", "corridor", [4, 3, 18, 5]),
    room("armory", "ARMORY", "armory", [4, 0, 9, 3]),
    room("cargo", "LOOT HOLD", "cargo", [9, 0, 14, 3]),
    room("lock", "AIRLOCK", "airlock", [14, 0, 18, 3]),
    room("crew", "CREW", "quarters", [4, 5, 9, 8]),
    room("mess", "MESS", "galley", [9, 5, 14, 8]),
    room("shop", "WORKSHOP", "workshop", [14, 5, 18, 8]),
    room("bridge", "BRIDGE", "bridge", [18, 0, 22, 8]),
  ],
  edges: [
    door("d-eng", [4, 3], [4, 5], "door.blast"),
    door("d-armory", [5, 3], [7, 3], "door.blast"),
    door("d-cargo", [10, 3], [12, 3]),
    door("d-lock", [15, 3], [17, 3], "door.airlock"),
    door("d-crew", [5, 5], [7, 5]),
    door("d-mess", [10, 5], [12, 5], "door.sliding"),
    door("d-shop", [15, 5], [17, 5]),
    door("d-bridge", [18, 3], [18, 5], "door.blast"),
  ],
  mounts: [
    face("block", "thrust-block.lg", "aft", [0, 1.5]),
    face("salvage-md", "ion-drive.salvaged.md", "aft", [0, 5]),
    face("rcs", "rcs.sm", "aft", [0, 7]),
    face("pod-drive", "ion-drive.salvaged.sm", "aft", [4, 9.5]),
    face("gun-s", "side-cannon.sm", "starboard", [8, -2]),
    face("gun-p", "side-cannon.md", "port", [7, 11]),
    opening("cargo-door", "cargo-door.2m", "starboard", [13, 0]),
    opening("lock", "airlock.exterior.md", "starboard", [16, 0]),
    top("ac", "autocannon.lg", [5, 1]),
    top("missiles", "missile-pod.md", [9, 9]),
    top("flak", "flak-cannon.sm", [15, 3.5]),
    top("clamp", "docking-clamp.md", [19, 3]),
    top("rad-lg", "radiator.lg", [1, 1]),
    top("rad-md", "radiator.md", [1, 5]),
    top("rad-pod", "radiator.md", [5, 9]),
    module("helm", "console.navigation.sm", [20, 3.5], "fore"),
    module("fire", "console.fire-control.sm", [19, 6], "fore"),
    module("core", "computer-core.md", [19, 1], "port"),
    module("reactor", "reactor.md", [0.5, 2.5], "fore"),
    module("life", "life-support.sm", [0.5, 0.5], "fore"),
    module("mag", "magazine.ballistic.md", [5, 0.5], "fore"),
    module("bunk-1", "crew-bunk.sm", [4.5, 6.5], "starboard"),
    module("bunk-2", "crew-bunk.sm", [6.5, 6.5], "starboard"),
  ],
  markings: { name: "MARAUDER", number: "RJ-66", emblem: "skull" },
});

/** Large: jawed pirate carrier with twin salvage pods. */
export const RJ_MAW = prefab({
  id: "rj.l.maw",
  name: "Maw",
  description: "Riftjack capital raider: mandible jaws around a salvage arm, lopsided armoured pods and three mismatched XL/LG drives.",
  faction: "Riftjack",
  role: "Carrier raider",
  theme: "riftjack",
  sizeClass: "L",
  volumes: [
    volume("hull", "hull", "deck", polygonTiles([[0, 0], [28, 0], [32, 2], [32, 12], [28, 14], [0, 14]]), { spine: true }),
    volume("jaw-s", "plate", "wing", polygonTiles([[32, 2], [38, 0], [38, 2], [34, 4], [32, 4]])),
    volume("jaw-p", "plate", "wing", polygonTiles([[32, 10], [34, 10], [38, 12], [38, 14], [32, 12]])),
    volume("pod-s", "hull", "pod", polygonTiles([[4, -4], [20, -4], [24, 0], [4, 0]]), { logo: false }),
    volume("pod-p", "hull", "pod", polygonTiles([[6, 14], [22, 14], [18, 18], [6, 18]]), { logo: false }),
  ],
  rooms: [
    room("eng", "ENGINES", "engineering", [0, 0, 6, 14]),
    room("hall", "GANGWAY", "corridor", [6, 6, 28, 8]),
    room("armory", "ARMORY", "armory", [6, 0, 11, 6]),
    room("cargo", "LOOT HOLD", "cargo", [11, 0, 17, 6]),
    room("cargo-2", "SCRAP BAY", "cargo", [17, 0, 22, 6]),
    room("lock", "AIRLOCK", "airlock", [22, 0, 26, 6]),
    room("shop", "CUTTERS", "workshop", [26, 0, 28, 6]),
    room("q1", "BUNKS", "quarters", [6, 8, 10, 14]),
    room("q2", "BUNKS", "quarters", [10, 8, 14, 14]),
    room("mess", "MESS", "galley", [14, 8, 18, 14]),
    room("den", "DEN", "lounge", [18, 8, 23, 14]),
    room("med", "SAWBONES", "medbay", [23, 8, 28, 14]),
    room("bridge", "BRIDGE", "bridge", [28, 0, 32, 14]),
  ],
  edges: [
    door("d-eng", [6, 6], [6, 8], "door.blast"),
    door("d-armory", [7, 6], [9, 6], "door.blast"),
    door("d-cargo", [13, 6], [15, 6]),
    door("d-cargo-2", [18, 6], [20, 6]),
    door("d-lock", [23, 6], [25, 6], "door.airlock"),
    door("d-shop", [26, 6], [28, 6]),
    door("d-q1", [7, 8], [9, 8]),
    door("d-q2", [11, 8], [13, 8]),
    door("d-mess", [15, 8], [17, 8], "door.sliding"),
    door("d-den", [19, 8], [21, 8]),
    door("d-med", [24, 8], [26, 8], "door.sliding"),
    door("d-bridge", [28, 6], [28, 8], "door.blast"),
    edge("h-cargo", [17, 0], [17, 6], "wall.half"),
  ],
  mounts: [
    face("rcs-bow-p", "rcs.sm", "port", [33.5, 4]),
    face("rcs-bow-s", "rcs.sm", "starboard", [33.5, 10]),
    face("rcs-stern-p", "rcs.sm", "port", [0.5, 14]),
    face("rcs-stern-s", "rcs.sm", "starboard", [0.5, 0]),
    face("xl-salvage", "ion-drive.salvaged.xl", "aft", [0, 3]),
    face("lg-salvage", "ion-drive.salvaged.lg", "aft", [0, 7]),
    face("xl-block", "thrust-block.xl", "aft", [0, 11]),
    face("pod-s-drive", "thrust-block.md", "aft", [4, -2]),
    face("pod-p-drive", "thrust-block.md", "aft", [6, 16]),
    face("gun-s-1", "side-cannon.md", "starboard", [10, -4]),
    face("gun-s-2", "side-cannon.md", "starboard", [14, -4]),
    face("gun-p", "side-cannon.md", "port", [10, 18]),
    face("torpedo", "torpedo-launcher.md", "port", [14, 18]),
    face("salvage-arm", "salvage-arm.md", "fore", [32, 7]),
    opening("lock", "airlock.exterior.md", "starboard", [25, 0]),
    top("ac", "autocannon.lg", [7, 1]),
    top("plasma", "plasma-turret.lg", [15, 9]),
    top("missiles-s", "missile-pod.lg", [8, -4]),
    top("missiles-p", "missile-pod.md", [12, 15]),
    top("flak", "flak-cannon.md", [12, 2]),
    top("pd", "point-defense.md", [20, 2]),
    top("clamp", "docking-clamp.lg", [29, 5]),
    top("rad-1", "radiator.lg", [1, 1]),
    top("rad-2", "radiator.lg", [1, 10]),
    top("rad-3", "radiator.md", [2, 6]),
    top("rad-4", "radiator.lg", [16, -3]),
    top("rad-5", "radiator.lg", [8, 15]),
    module("helm", "console.navigation.sm", [30, 6.5], "fore"),
    module("fire", "console.fire-control.sm", [30, 3], "fore"),
    module("command", "console.command.sm", [29, 9], "fore"),
    module("core", "computer-core.lg", [28, 1], "port"),
    module("reactor", "reactor.lg", [1, 1], "fore"),
    module("reactor-2", "reactor.md", [1, 9], "fore"),
    module("life", "life-support.md", [5, 1], "fore"),
    module("shieldgen", "shield-generator.md", [4, 10], "fore"),
    module("mag", "magazine.missile.lg", [6.5, 0.5], "fore"),
    module("bunk-1", "crew-bunk.sm", [6.5, 12.5], "starboard"),
    module("bunk-2", "crew-bunk.sm", [6.5, 10.5], "starboard"),
    module("bunk-3", "crew-bunk.sm", [10.5, 12.5], "starboard"),
    module("bunk-4", "crew-bunk.sm", [10.5, 10.5], "starboard"),
  ],
  markings: { name: "MAW", number: "RJ-01", emblem: "skull" },
});
