import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { TILESET_WALL_CONVENTION as c } from "../packages/content/src/tileset-interfaces";
const sourcePath = "packages/content/src/construction-floor-interfaces.json";
const source = readFileSync(sourcePath, "utf8"),
  floor = JSON.parse(source);
const spec = {
  schema: "sidereal.tileset-roof-request.v1",
  wallConvention: c.schema,
  latticePerMeter: c.latticePerMeter,
  moduleUnits: c.moduleUnits,
  standardDeck: c.standardDeck,
  sourceFloorInterfaces: {
    path: sourcePath,
    sha256: createHash("sha256").update(source).digest("hex"),
  },
  sourceFrame: "Blender XY floor plane, Z up; metres; applied transforms",
  modelOrigin:
    "floor footprint origin at roof underside; no inherited legacy roof elevation",
  placementUndersideUnits:
    c.standardDeck.floorThicknessUnits + c.standardDeck.clearHeightUnits,
  reservationHeightUnits: c.standardDeck.roofThicknessUnits,
  profiles: {
    bearing: "inset250-wall-cap-v1",
    edge: "roof-flat-4-v1",
    top: "roof-service-reservation-v1",
  },
  exportToleranceMeters: 0.000001,
  tolerancePurpose: "float encoding only; exact nominal seams",
  shapes: floor.parts.map(
    (p: { id: string; footprint: [number, number][] }) => ({
      id: p.id,
      footprintUnits: p.footprint,
      reservationZUnits: [0, c.standardDeck.roofThicknessUnits],
      allowedQuarterTurns: [0, 1, 2, 3],
      reflection: "requires-export-validation",
    }),
  ),
  requirements: [
    "All visible trim, lights, backing and underside within polygon extrusion, including reimported GLB nodes",
    "Continuous backing across declared roof coverage; adjacent native mating planes meet without scaling or nudges",
    "Every contact, seal, collision, damage and service role remains separate and unqualified until assembled proof",
    "Editable native Blender source, material-preserving GLB, all-node containment, exact source/spec/export hashes",
    "Actual opaque-background top, underside, each shape and assembled square/diagonal/taper seam captures",
    "Preserve existing roof r001 and floor r002; no catalogs, live pins or releases changed",
  ],
  approval: "unapproved",
  gameplayQualification: "pending",
};
const json = JSON.stringify(spec, null, 2) + "\n",
  path = "packages/content/src/ship-tileset-roof-spec.v1.json";
const guide = `# Ship tileset roof authoring requirements

Generated by scripts/generate_ship_tileset_roof_spec.ts from the approved dimensional constant and pinned native floor footprints.

Specification: ship-tileset-roof-spec.v1.json, SHA-256 ${createHash("sha256").update(json).digest("hex")}.

The twelve footprint polygons and their origins match the floor interface source exactly. Source XY is the deck plane and Z is height in metres. The complete visible roof occupies Z=0…0.125 m, including backing, trim, lights and underside details. Its model origin is the roof underside; standard placement is 3.1875 m above floor-bottom. The top is 3.3125 m; the service void ends at 3.5 m. Neither the 3 m clear height nor the 0.1875 m service void may absorb roof decoration.

Every exported primitive and transformed child node must remain inside the declared polygon extrusion. Nominal mating planes meet exactly. The 1 µm allowance is for float encoding only. Preserve editable Blender topology and authored materials, textures and normals. The legacy roof r001 has a different total visual reservation; do not move or scale it into this one.

Deliver each shape plus square, diagonal and taper seam assemblies; use opaque-background captures from top, underside and oblique views. Pin source/spec/export hashes and preserve earlier revisions. Collision, bearing, seal, damage and service metadata are separate from visual surfaces and remain unqualified until exact assembled proof. All new art remains unapproved; this request changes no live native or collision pin.
`;
for (const [target, body] of [
  [path, json],
  ["docs/ship_tileset_roof_authoring_requirements.md", guide],
]) {
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== body)
      throw Error(`Stale roof request: ${target}`);
  } else writeFileSync(target, body);
}

console.log(
  JSON.stringify({
    sha256: createHash("sha256").update(json).digest("hex"),
    shapes: spec.shapes.length,
  }),
);
