import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { TILESET_WALL_CONVENTION } from "../packages/content/src/tileset-interfaces";

const c = TILESET_WALL_CONVENTION;
const spec = {
  ...c,
  sourceFrame: "Blender X run, Y inward, Z up; metres; applied transforms",
  rendererFrame: "source (x,y,z) becomes renderer (x,z,-y)",
  modelOrigin: "outer edge start at wall bottom; place at deck floor-top datum",
  exportToleranceMeters: 0.000001,
  tolerancePurpose: "float encoding only; nominal seams coincide exactly",
  profiles: {
    end: "inset250-wall-end-v1",
    floor: "inset250-wall-bearing-v1",
    top: "inset250-wall-cap-v1",
    exterior: "inset250-external-mating-plane-v1",
  },
  shapes: [32, 64].flatMap((lengthUnits) =>
    c.heightQuarters.map((q) => ({
      id: `straight-${lengthUnits / c.latticePerMeter}m-q${q}`,
      lengthUnits,
      heightUnits: (c.standardDeck.clearHeightUnits * q) / 4,
      reservationUnits: {
        min: [0, 0, 0],
        max: [
          lengthUnits,
          c.thicknessUnits,
          (c.standardDeck.clearHeightUnits * q) / 4,
        ],
      },
      placementFloorTopUnits: c.standardDeck.floorThicknessUnits,
      allowedQuarterTurns: [0, 1, 2, 3],
      reflection: "requires-export-validation",
      damageMode: "voxel",
      gameplayQualification: "pending",
    })),
  ),
  standardDatumsUnits: {
    floorBottom: 0,
    floorTop: 6,
    wallTop: 102,
    roofTop: 106,
    serviceTop: 112,
  },
  smallerDeckPolicy:
    "Explicit per-deck clear height and pitch; reused wall heights require matching native floor/roof/closure. Actor traversal is qualified separately; short ducts do not grant crawling.",
  requiredOutputs: [
    "editable .blend",
    "material-preserving GLB",
    "exact source/spec/export hashes",
    "all-node exported containment",
    "separate contact/collision/seal/damage data",
    "assembled native seam renders",
    "explicit unapproved art status",
  ],
};
const json = JSON.stringify(spec, null, 2) + "\n";
const hash = createHash("sha256").update(json).digest("hex");
const rows = spec.shapes
  .map(
    (s) =>
      `| ${s.id} | ${s.lengthUnits / 32} | ${s.heightUnits / 32} | 0…0.25 inward |`,
  )
  .join("\n");
const guide = `# Ship tileset authoring requirements\n\nGenerated by \`scripts/generate_ship_tileset_wall_spec.ts\`; do not hand-edit.\n\nSpecification: \`ship-tileset-wall-spec.v1.json\`, SHA-256 \`${hash}\`.\nExtends \`${c.baseInterfaceSchema}\`; this is the first straight-wall request, not the complete qualified tileset.\n\nThe owner approved 250 mm **inside** the tile and the standard vertical dimensions on 2026-09-11. Tile edges are fixed external mating planes. Standard deck: 0.1875 m floor + 3 m clear height + 0.125 m roof + 0.1875 m service void = 3.5 m pitch. Partial wall heights are 0.75/1.5/2.25/3 m. Smaller decks are explicit profiles; short spaces require independent actor clearance/traversal qualification.\n\nBlender frame: X along the run, Y inward, Z up, metres. Model origin is the outer edge start at the wall bottom. Standard placement Z is 0.1875 m. Full-height wall top is 3.1875 m; roof top 3.3125 m; next slab bottom 3.5 m. Apply transforms; preserve materials. No source recentering, scaling or per-placement adjustment.\n\n| Shape | Length m | Height m | Reservation Y m |\n| --- | --- | --- | --- |\n${rows}\n\nEvery exported primitive/node must fit the complete reservation, including handles, panels and trim. End planes X=0/length, exterior Y=0, bottom Z=0 and top Z=height are exact declared interfaces. End normals oppose; the exterior normal is -Y. A 1 µm tolerance permits float encoding only. Recessed decorative bevels require continuous backing where closure is intended. Adjacent pieces must not duplicate exposed coplanar faces.\n\nVisual, bearing, collision, seal, damage and service data remain separate. All gameplay adapters and all new art approval remain pending. Closed wall bands do not prove an enclosed room. Low cockpit sills need qualified glazing/frame/roof closure; short opaque walls alone do not seal a full-height compartment.\n\nPreserve the existing centred r004 and all historical sources. This request does not install assets, move legacy lockers or change live collision. Corners, diagonals, T/cross, openings, floor/roof, glazing and airlock companions require subsequent exact spec extensions and assembly fixtures before Contract A can pass.\n`;
for (const [path, body] of [
  ["packages/content/src/ship-tileset-wall-spec.v1.json", json],
  ["docs/ship_tileset_authoring_requirements.md", guide],
]) {
  if (process.argv.includes("--check")) {
    if (readFileSync(path, "utf8") !== body)
      throw Error(`Generated tileset requirements are stale: ${path}`);
  } else writeFileSync(path, body);
}
console.log(
  JSON.stringify({ specificationSha256: hash, shapes: spec.shapes.length }),
);
