import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { TILESET_WALL_CONVENTION as c } from "../packages/content/src/tileset-interfaces";
const width = c.thicknessUnits / 32,
  half = width / 2;
const core = {
  id: "internal-core",
  reservationPolygonM: [
    [-half, -half],
    [half, -half],
    [half, half],
    [-half, half],
  ],
};
const cap = {
  id: "internal-end",
  reservationPolygonM: [
    [0, -half],
    [half, -half],
    [half, half],
    [0, half],
  ],
};
const shapes = [
  core,
  cap,
  ...[0.75, 0.875, 1, 1.75, 1.875, 2].map((length) => ({
    id: `internal-span-${length}`,
    lengthM: length,
    reservationPolygonM: [
      [0, -half],
      [length, -half],
      [length, half],
      [0, half],
    ],
  })),
];
const spec = {
  schema: "sidereal.tileset-internal-junction-request.v1",
  wallConvention: c.schema,
  latticePerMeter: 32,
  thicknessM: width,
  reservation: "explicit-centered-internal-partition-only",
  halfThicknessM: half,
  sourceFrame:
    "Blender X along line, Y across line, Z up; metres; origin is graph node or first span end",
  heightsM: c.heightQuarters.map(
    (q) => (c.standardDeck.clearHeightUnits * q) / 128,
  ),
  placementFloorTopM: c.standardDeck.floorThicknessUnits / 32,
  shapes,
  junctionProfiles: [
    { id: "end", part: "internal-end", rays: [[1, 0]], cutbackM: half },
    {
      id: "corner",
      part: "internal-core",
      rays: [
        [1, 0],
        [0, 1],
      ],
      cutbackM: half,
    },
    {
      id: "tee",
      part: "internal-core",
      rays: [
        [-1, 0],
        [1, 0],
        [0, 1],
      ],
      cutbackM: half,
    },
    {
      id: "cross",
      part: "internal-core",
      rays: [
        [-1, 0],
        [1, 0],
        [0, 1],
        [0, -1],
      ],
      cutbackM: half,
    },
  ],
  fixtures: [
    "isolated capped 1m and2m wall",
    "right-angle corner with1m and2m branches",
    "T with three2m branches",
    "cross with four2m branches",
  ],
  allowedQuarterTurns: [0, 1, 2, 3],
  exportToleranceMeters: 0.000001,
  tolerancePurpose: "float encoding only; exact perpendicular mate planes",
  requirements: [
    "Core owns junction volume once; straight arms terminate at the half-thickness planes, never pass through core",
    "End cap terminates at the authored endpoint plane and extends only toward its connected span",
    "Full imported GLB node and face containment, correct closed contacts and negative gap/overlap controls",
    "Native Blender continuous backing, inset panels, pinned PBR preservation, editable source and opaque assembled renders",
    "Separate native visible geometry and unqualified collision/seal/damage/bearing roles",
  ],
  unsupported: [
    "inward exterior boundary use",
    "internal left/right unilateral reservations",
    "angled internal junctions",
    "internal-to-exterior junction adapters",
    "doors/openings",
    "generic native installation and pressure",
  ],
  approval: "unapproved",
};
const json = JSON.stringify(spec, null, 2) + "\n",
  sha = createHash("sha256").update(json).digest("hex");
const guide = `# Centered internal junction native request

Generated by scripts/generate_ship_tileset_internal_spec.ts. Specification SHA-256: ${sha}.

This family applies only to explicitly centered internal partitions. It is not an exterior wall convention. The 250 mm body occupies Y=-0.125…0.125 m about the directed line. Source X runs along the line and Z is up. Standard floor-top placement is0.1875 m; height variants are0.75/1.5/2.25/3 m.

One0.25 ×0.25 m core owns each orthogonal corner/T/cross volume; branches end on perpendicular planes0.125 m from the node. Never run duplicated walls through the core. End caps have only0.125 m length toward their connected branch and terminate exactly at the authored endpoint. The request includes resulting short native spans; no placed scaling or nudging is allowed.

All visible trim and continuous backing must fit the declared extrusion. Preserve authored Blender surfaces/materials and exact source/spec/export hashes. Validate all GLB primitives, actual complete contacts, gap/overlap negative controls and assembled capped/corner/T/cross views. Physical role metadata is separate and remains unqualified. Side-specific internal reservations, angled nodes, exterior ties and openings need separate adapters. All art is unapproved; no live assets or schemas are changed by this request.
`;
for (const [path, body] of [
  ["packages/content/src/ship-tileset-internal-spec.v1.json", json],
  ["docs/ship_tileset_internal_authoring_requirements.md", guide],
]) {
  if (process.argv.includes("--check")) {
    if (readFileSync(path, "utf8") !== body)
      throw Error(`Stale internal request: ${path}`);
  } else writeFileSync(path, body);
}
console.log(JSON.stringify({ sha256: sha, shapes: shapes.length }));
