"""Pin the exact audited native room for opt-in construction review, never refit live ships."""
from pathlib import Path
import argparse
import hashlib
import json
import subprocess

ROOT = Path(__file__).resolve().parents[1]
AUDIT = ROOT / 'assets/art-library/designs/shipyard.structure.boundary-kit/revisions/r006/qualification-a007/native-room-validation.json'
AUDIT_SHA = 'f347642d4ae424e63fa5abe0326f2e6cf0d82a5f168f0191c878f327056eec4e'
HISTORICAL_ROOT = Path('/root/sidereal_spacetime')


def source_path(pin_path):
    # The immutable audit retains its original authoring checkout paths. Resolve
    # that known historical prefix locally without changing the hashed bytes.
    path = Path(pin_path)
    if path.is_relative_to(HISTORICAL_ROOT):
        path = path.relative_to(HISTORICAL_ROOT)
    return ROOT / path


def install(check=False):
    raw = AUDIT.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == AUDIT_SHA, 'Native audit changed'
    audit = json.loads(raw)
    assert audit['pass'] and audit['qualification']['exteriorEnclosed'] and audit['qualification']['closedDoorAirtight']
    used = {p['source'] for p in audit['placements']}
    sources = {}
    outputs = {}
    for key, pin in audit['sourcePins'].items():
        source = source_path(pin['path'])
        assert hashlib.sha256(source.read_bytes()).hexdigest() == pin['sha256'], key
        if key in used:
            assert source.suffix == '.glb'
            destination = ROOT / 'assets/runtime/construction/pressure-room-r006' / (key + '.glb')
            sources[key] = {'url': '/assets/construction/pressure-room-r006/' + key + '.glb', 'sha256': pin['sha256']}
            outputs[destination] = source.read_bytes()
    # Retain the exact audit text for runtime hash verification. No native binary
    # data is embedded in the world module or accepted through reducer inputs.
    content = '/* Generated by install_construction_pressure_room.py; exact audited candidate. */\n'
    content += 'export const NATIVE_PRESSURE_ROOM_AUDIT_TEXT = ' + json.dumps(raw.decode()) + ';\n'
    content += 'export const NATIVE_PRESSURE_ROOM_SOURCES = ' + json.dumps(sources) + ' as const;\n'
    content += 'export const NATIVE_PRESSURE_ROOM_PIN = ' + json.dumps({'id':'native-pressure-room','revision':'r006-a007','sha256':AUDIT_SHA}) + ' as const;\n'
    content_path = ROOT / 'packages/content/src/construction-pressure-room.ts'
    # Format before both writing and comparing, using the project's installed
    # formatter/config so --check verifies the exact checked-in representation.
    formatted = subprocess.run(
        ['node', str(ROOT / 'node_modules/prettier/bin/prettier.cjs'),
         '--stdin-filepath', str(content_path)],
        input=content, text=True, capture_output=True, check=True, cwd=ROOT,
    ).stdout
    outputs[content_path] = formatted.encode()
    manifest = {'schema':'sidereal.native-pressure-room-runtime.v1','auditSha256':AUDIT_SHA,'sources':sources,'status':'opt-in qualified review fixture; not final art approval, live Wayfarer refit or general airtightness','placementCount':len(audit['placements'])}
    outputs[ROOT / 'assets/runtime/construction/pressure-room-r006/manifest.json'] = (json.dumps(manifest,indent=2)+'\n').encode()
    for target, data in outputs.items():
        if check:
            assert target.read_bytes() == data, str(target)
        else:
            target.parent.mkdir(parents=True,exist_ok=True)
            target.write_bytes(data)
    print(json.dumps({'nativeSourcesVerified':len(audit['sourcePins']),'runtimeGlbs':len(sources),'placements':len(audit['placements']),'check':check}))

if __name__ == '__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    install(parser.parse_args().check)
