"""Install the exact native ladder for opt-in gameplay review; never refit a ship."""
from pathlib import Path
import argparse
import hashlib
import json
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/art-library/designs/shipyard.structure.traversal-ladder/revisions/r000/a003'
AUDIT_SHA = 'a41e28d065833c1be30ae1e1e5a4a49832b0771157e6a80b1343f82ccec9e714'
COLLISION_SHA = '61e4c100d8649d468fd1b0758bcfb2a5b9a6b8b78583b7818439a7b77199e5a9'

def install(check=False):
    audit = (SOURCE / 'traversal-audit.json').read_bytes()
    collision = (SOURCE / 'collision-envelopes.json').read_bytes()
    assert hashlib.sha256(audit).hexdigest() == AUDIT_SHA
    assert hashlib.sha256(collision).hexdigest() == COLLISION_SHA
    delivery = json.loads((SOURCE / 'delivery.json').read_bytes())
    assert delivery['auditSha256'] == AUDIT_SHA
    assert delivery['status'] == 'native-geometry-qualified'
    sources, outputs = {}, {}
    for key, pin in delivery['sources'].items():
        source = ROOT / pin['path']
        data = source.read_bytes()
        assert hashlib.sha256(data).hexdigest() == pin['sha256'], key
        sources[key] = {'url': f'/assets/construction/traversal-r000-a003/{key}.glb', 'sha256': pin['sha256']}
        outputs[ROOT / f'assets/runtime/construction/traversal-r000-a003/{key}.glb'] = data
    pin = {'id': delivery['adapterId'], 'revision': delivery['revision'], 'sha256': AUDIT_SHA}
    values = {'AUDIT_TEXT': audit.decode(), 'DELIVERY': delivery, 'SOURCES': sources,
              'PIN': pin, 'COLLISION': json.loads(collision)}
    content = '/* Generated by install_construction_traversal_runtime.py. Qualified review only. */\n'
    for key, value in values.items():
        content += f'export const NATIVE_TRAVERSAL_ROOM_{key} = ' + json.dumps(value) + ' as const;\n'
    content = subprocess.run([str(ROOT / 'node_modules/.bin/prettier'), '--stdin-filepath', 'traversal.ts'], input=content, text=True, capture_output=True, check=True).stdout
    outputs[ROOT / 'packages/content/src/construction-traversal-room.ts'] = content.encode()
    manifest = {'pin': pin, 'sources': sources, 'collisionSha256': COLLISION_SHA,
                'status': 'opt-in native traversal review; not normal Wayfarer refit or final art approval'}
    outputs[ROOT / 'assets/runtime/construction/traversal-r000-a003/manifest.json'] = (json.dumps(manifest, indent=2)+'\n').encode()
    for path, data in outputs.items():
        if check:
            assert path.read_bytes() == data, path
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print(json.dumps({'sources': len(sources), 'placements': len(json.loads(audit)['parts']), 'check': check}))

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    install(parser.parse_args().check)
