"""Verify pinned stair sources and stage their content contract; no service publication.

Default writes only the generated content module. --stage-assets additionally copies
exact authored GLBs into a private .runtime directory for the integration owner.
"""
from pathlib import Path
import argparse
import hashlib
import json
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/art-library/designs/shipyard.structure.stair-dogleg/revisions/r000/a003'
AUDIT_SHA = '8df56649474fa8379af3a2c678716fc1f80406e9f9457e85498598f6a0be9831'
SOURCE_SHAS = {
    'stair-kit': '8d2f8359f6221a43245fdd9b10671892cbe5d05f5ba8569ff04f1f8e54f728a7',
    'floor': '138b483f6052f01e23883b8d8b48bb72cdbace44727c8e717b1e6351c3593585',
    'roof': 'fe5646a431fcaa21033ca235094188b450c33e55e15735b7834fc18623fb3711',
}


def stage(check=False, stage_assets=False):
    audit = (SOURCE / 'stair-audit.json').read_bytes()
    assert hashlib.sha256(audit).hexdigest() == AUDIT_SHA
    delivery = json.loads((SOURCE / 'delivery.json').read_bytes())
    assert delivery['auditSha256'] == AUDIT_SHA
    assert delivery['status'] == 'native-geometry-qualified'
    assert set(delivery['sources']) == set(SOURCE_SHAS)
    sources, outputs = {}, {}
    for key, pin in delivery['sources'].items():
        path = (ROOT / pin['path']).resolve()
        assert path.is_relative_to(ROOT)
        data = path.read_bytes()
        assert hashlib.sha256(data).hexdigest() == pin['sha256'] == SOURCE_SHAS[key], key
        sources[key] = {'url': f'/assets/construction/stairs-r000-a003/{key}.glb', 'sha256': pin['sha256']}
        if stage_assets:
            outputs[ROOT / f'.runtime/art-library/stairs/r000-a003/{key}.glb'] = data
    pin = {'id': delivery['adapterId'], 'revision': delivery['revision'], 'sha256': AUDIT_SHA}
    values = {'AUDIT_TEXT': audit.decode(), 'DELIVERY': delivery, 'SOURCES': sources, 'PIN': pin}
    content = '/* Generated by stage_construction_stairs_runtime.py. Qualified fixture only; assets not published. */\n'
    for key, value in values.items():
        content += f'export const NATIVE_STAIR_ROOM_{key} = ' + json.dumps(value) + ' as const;\n'
    content = subprocess.run([str(ROOT / 'node_modules/.bin/prettier'), '--stdin-filepath', 'stairs.ts'], input=content, text=True, capture_output=True, check=True).stdout
    outputs[ROOT / 'packages/content/src/construction-stairs-room.ts'] = content.encode()
    for path, data in outputs.items():
        if check:
            assert path.read_bytes() == data, path
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print(json.dumps({'sources': len(sources), 'placements': len(json.loads(audit)['parts']), 'check': check, 'privateAssetsStaged': stage_assets, 'published': False}))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--stage-assets', action='store_true')
    args = parser.parse_args()
    stage(args.check, args.stage_assets)
