"""Stage a hash-pinned additive airlock integration. Never edits shared sources."""
import difflib, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
changes={}
def read(p):
    return changes.get(p,(ROOT/p).read_text())
def put(p,s):changes[p]=s
def replace(p,old,new):
    s=read(p)
    if s.count(old)!=1:raise RuntimeError(f'{p}: anchor count {s.count(old)} for {old[:80]!r}')
    put(p,s.replace(old,new,1))
def prefix(p,s):put(p,s+read(p))
def export(p,name,path):
    data=json.loads(read(p));data['exports'][name]=path;put(p,json.dumps(data,indent=2)+'\n')
content='packages/content/src/construction.ts';doc='packages/sim/src/construction-airlock-document.ts'
s=read(doc);a=s.index('export interface NativeAirlockBinding');b=s.index('export type NativeAirlockDocument',a);interface=s[a:b]
replace(content,'export interface NativeStairRoomBinding',interface+'export interface NativeStairRoomBinding')
replace(content,'  stairRoom?: NativeStairRoomBinding;','  stairRoom?: NativeStairRoomBinding;\n  /** Exact two-door native composite, with separately accepted atmosphere and manual actuators. */\n  airlockRoom?: NativeAirlockBinding;')
put(doc,s[:a]+'export type { NativeAirlockBinding } from "@sidereal/content/construction";\nimport type { NativeAirlockBinding } from "@sidereal/content/construction";\n'+s[b:])
export('packages/content/package.json','./construction-airlock-room','./src/construction-airlock-room.ts')
export('packages/sim/package.json','./construction-airlock-published','./src/construction-airlock-published.ts')
replace('packages/sim/src/construction-airlock-published.ts','../../content/src/construction-airlock-room','@sidereal/content/construction-airlock-room')
p='packages/sim/src/construction-airlock-document.test.ts';replace(p," // Shared parser must reject until ALL matching authority/native adapters land.\n expect(()=>readConstructionDraft(JSON.stringify(d))).toThrow('Unsupported');"," // Shared parser accepts only the exact bound native fixture.\n expect(JSON.parse(readConstructionDraft(JSON.stringify(d)).canonical).airlockRoom).toEqual(d.airlockRoom);")
p='packages/sim/src/construction-transactions.ts';prefix(p,'import { readNativeAirlockDocument } from "./construction-airlock-document";\n');replace(p,'          "stairRoom",','          "stairRoom",\n          "airlockRoom",');replace(p,'  if (input.stairRoom !== undefined) {','  if (input.airlockRoom !== undefined) {\n    readNativeAirlockDocument(JSON.stringify(normalized));\n    normalized.airlockRoom!.parts.sort((a,b)=>a.sourcePartIndex-b.sourcePartIndex);\n    normalized.airlockRoom!.roofTileIds.sort(compareText);\n    normalized.airlockRoom!.exteriorTileIds.sort(compareText);\n  }\n  if (input.stairRoom !== undefined) {')
p='packages/sim/src/construction-instance.ts';prefix(p,'import { nativeAirlockCollision, readNativeAirlockDocument } from "./construction-airlock-document";\nimport { compilePublishedNativeExternalAirlock } from "./construction-airlock-published";\n');replace(p,'!(source.traversalRoom || source.stairRoom)','!(source.traversalRoom || source.stairRoom || source.airlockRoom)');replace(p,'  const collision = resolveDeckCollision(','  const collision = source.airlockRoom\n    ? nativeAirlockCollision(readNativeAirlockDocument(verified.canonical), compilePublishedNativeExternalAirlock(source.layout.id), [])\n    : resolveDeckCollision(');replace(p,'    source.stairRoom\n      ? [','    source.airlockRoom?.parts ?? [],\n    source.stairRoom\n      ? [');replace(p,'source.traversalRoom?.parts ?? source.stairRoom?.parts ?? []','source.traversalRoom?.parts ?? source.stairRoom?.parts ?? source.airlockRoom?.parts ?? []');replace(p,'  if (spawned.stairRoom)\n','  if (spawned.airlockRoom) {\n    const a=spawned.airlockRoom; a.deckId=mapped(a.deckId); a.innerDoorId=mapped(a.innerDoorId); a.outerDoorId=mapped(a.outerDoorId);\n    for(const p of a.parts)p.id=mapped(p.id);\n    a.roofTileIds=a.roofTileIds.map(mapped); a.exteriorTileIds=a.exteriorTileIds.map(mapped);\n  }\n  if (spawned.stairRoom)\n')
p='packages/world/src/construction-instances.ts';prefix(p,'import { installNativeAirlock } from "./construction-airlock";\nimport { bindNativeAirlockPlan, readNativeAirlockDocument } from "@sidereal/sim/construction-airlock-document";\nimport { compilePublishedNativeExternalAirlock } from "@sidereal/sim/construction-airlock-published";\n');replace(p,'  installDoors(ctx, plan.instanceId, plan.document);','  installDoors(ctx, plan.instanceId, plan.document);\n  if(plan.document.airlockRoom) {\n    const native=bindNativeAirlockPlan(readNativeAirlockDocument(JSON.stringify(plan.document)),compilePublishedNativeExternalAirlock,plan.instanceId);\n    installNativeAirlock(ctx,plan.instanceId,native.installation,compilePublishedNativeExternalAirlock);\n  }')
p='packages/world/src/construction-doors.ts';prefix(p,'import { requestNativeAirlockDoor, acceptedNativeAirlockCollision, ownNativeAirlocks } from "./construction-airlock";\nimport { compilePublishedNativeExternalAirlock } from "@sidereal/sim/construction-airlock-published";\n');replace(p,'  if (document.pressureRoom) {','  if (document.airlockRoom) return; // Exact two-door installation owns both frames.\n  if (document.pressureRoom) {');replace(p,'  const key = instance.id + ":" + instance.revision + ":" + deckId;','  if ((JSON.parse(instance.documentJson) as ConstructionDocument).airlockRoom)\n    return acceptedNativeAirlockCollision(ctx,instance,deckId,compilePublishedNativeExternalAirlock);\n  const key = instance.id + ":" + instance.revision + ":" + deckId;');replace(p,'  const actor = [...ctx.db.character.by_owner.filter(ctx.sender)][0],','  if(requestNativeAirlockDoor(ctx,args,compilePublishedNativeExternalAirlock))return;\n  const actor = [...ctx.db.character.by_owner.filter(ctx.sender)][0],');replace(p,'  for (const door of ctx.db.constructionDoor.by_moving.filter(true)) {','  for (const door of ctx.db.constructionDoor.by_moving.filter(true)) {\n    if(ctx.db.constructionAirlock.id.find(door.instanceId))continue;');replace(p,'  return [...ctx.db.constructionInstance.by_owner.filter(ctx.sender)].flatMap(','  const acceptedAirlocks=new Set(ownNativeAirlocks(ctx).map(a=>a.id));\n  return [...ctx.db.constructionInstance.by_owner.filter(ctx.sender)].filter(i=>!ctx.db.constructionAirlock.id.find(i.id)||acceptedAirlocks.has(i.id)).flatMap(')
p='packages/world/src/construction-native-pressure.ts';prefix(p,'import { scopedAtmosphereTable } from "./construction-atmosphere-scope";\n');replace(p,'  const gasChanges = stepAtmosphere(\n    ctx.db.constructionAtmosphere,','  const gasChanges = stepAtmosphere(\n    scopedAtmosphereTable(ctx.db.constructionAtmosphere, installations.map(i=>i.id)),')
p='packages/world/src/index.ts';prefix(p,'import * as nativeAirlock from "./construction-airlock";\nimport { compilePublishedNativeExternalAirlock } from "@sidereal/sim/construction-airlock-published";\n');replace(p,'  constructionInteractionBinding:\n','  constructionAirlock: nativeAirlock.constructionAirlock,\n  constructionInteractionBinding:\n');replace(p,'    nativePressure.stepNativePressure(ctx, compilePublishedNativePressureRoom);','    nativePressure.stepNativePressure(ctx, compilePublishedNativePressureRoom);\n    nativeAirlock.stepNativeAirlocks(ctx, compilePublishedNativeExternalAirlock);');put(p,read(p)+'\nexport const ownNativeAirlocks = db.view({name:"own_native_airlocks",public:true},t.array(nativeAirlock.nativeAirlockProjection),auth.gameView(nativeAirlock.ownNativeAirlocks));\n')
output=ROOT/'.runtime/airlock-shared-preview.json';output.parent.mkdir(exist_ok=True);output.write_text(json.dumps({str(ROOT/p):s for p,s in changes.items()}))
manifest={p:{'beforeSha256':hashlib.sha256((ROOT/p).read_bytes()).hexdigest(),'afterSha256':hashlib.sha256(s.encode()).hexdigest()}for p,s in changes.items()}
(ROOT/'docs/handoffs/native_external_airlock_patch_inputs.json').write_text(json.dumps(manifest,indent=2)+'\n')
patch=''.join(''.join(difflib.unified_diff((ROOT/p).read_text().splitlines(True),s.splitlines(True),fromfile='a/'+p,tofile='b/'+p))for p,s in changes.items())
(ROOT/'docs/handoffs/native_external_airlock_integration.patch').write_text(patch)
print(f'Staged {len(changes)} files; shared source untouched.')
