import { expect, test, vi } from "vitest";
import { NullEngine } from "@babylonjs/core/Engines/nullEngine";
import { Scene } from "@babylonjs/core/scene";
import { TransformNode } from "@babylonjs/core/Meshes/transformNode";
import { CreateBox } from "@babylonjs/core/Meshes/Builders/boxBuilder";
import { Vector3 } from "@babylonjs/core/Maths/math.vector";
import { cacheStaticTransforms } from "./static-transform-cache";

test("static batches skip idle updates but follow moving ship roots with correct bounds", () => {
  const engine = new NullEngine(), scene = new Scene(engine);
  const ship = new TransformNode("ship", scene), deck = new TransformNode("deck", scene);
  deck.parent = ship;
  const mesh = CreateBox("batch", {}, scene);
  mesh.parent = deck;
  mesh.position.x = 3;
  mesh.metadata = { role: "hull", trianglePlacements: [{start:0,count:12,placementId:"a"}] };
  const update = vi.spyOn(mesh, "freezeWorldMatrix");
  const cache = cacheStaticTransforms(deck, [mesh]);
  expect(mesh.isWorldMatrixFrozen).toBe(true);
  for (let i = 0; i < 10; i++) cache.refresh();
  expect(update).toHaveBeenCalledTimes(1);
  ship.position.set(10, 2, -5);
  ship.rotation.y = 0.7;
  ship.scaling.set(2, 1, 0.5);
  scene.onBeforeRenderObservable.notifyObservers(scene);
  const expected = Vector3.TransformCoordinates(new Vector3(3, 0, 0), deck.getWorldMatrix());
  expect(Vector3.Distance(mesh.getAbsolutePosition(), expected)).toBeLessThan(1e-5);
  expect(Vector3.Distance(mesh.getBoundingInfo().boundingBox.centerWorld, expected)).toBeLessThan(1e-5);
  expect(update).toHaveBeenCalledTimes(2);
  deck.setEnabled(false);
  expect(mesh.isEnabled()).toBe(false);
  deck.setEnabled(true);
  mesh.visibility = 0.4;
  cache.refresh();
  expect(mesh.visibility).toBe(0.4);
  expect(mesh.metadata.trianglePlacements[0].placementId).toBe("a");
  cache.dispose();
  expect(mesh.isWorldMatrixFrozen).toBe(false);
  expect(mesh.doNotSyncBoundingInfo).toBe(false);
  scene.dispose(); engine.dispose();
});
